### ISSUE TITLE
Empty line in known_hosts file makes create_connection choke

### ISSUE THREAD

**Issue by nchammas** [ronf/asyncssh#12]
My `known_hosts` file somehow ended up having a leading blank line. This seems to cause `create_connection()` some trouble:

```
$ python3 asyncssh-example.py 
Traceback (most recent call last):
<snipped>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "asyncssh-example.py", line 8, in put_file
    conn, client = yield from asyncssh.create_connection(host=host, client_factory=None)
  File "/usr/local/lib/python3.4/site-packages/asyncssh/connection.py", line 3086, in create_connection
    local_addr=local_addr)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 643, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 655, in _create_connection_transport
    protocol = protocol_factory()
  File "/usr/local/lib/python3.4/site-packages/asyncssh/connection.py", line 3082, in <lambda>
    auth_waiter)
  File "/usr/local/lib/python3.4/site-packages/asyncssh/connection.py", line 1315, in __init__
    server_host_keys = self._parse_known_hosts(host, port)
  File "/usr/local/lib/python3.4/site-packages/asyncssh/connection.py", line 1378, in _parse_known_hosts
    dest_hosts, key = line.split(None, 1)
ValueError: need more than 0 values to unpack
```

This is my environment:

```
$ python3 --version
Python 3.4.3
$ pip show asyncssh
---
Name: asyncssh
Version: 0.9.2
Location: /usr/local/lib/python2.7/site-packages
Requires: 
```

A `known_hosts` file probably shouldn't have blank lines, but I think AsyncSSH should be able to handle them without choking.

**Comment by ronf** [comment]
Agreed on this, and in fact this is already fixed in the "develop" branch. The initial version I did was quite primitive and didn't support blank lines or explicitly skip over comment lines. The new version handles both of these cases, and returns a more explicit error if it finds non-commented lines that are not well-formed. It also includes some improvements proposed by Alexander Travov to handle negated patterns, hashed entries, and handling of "@cert-authority" and "@revoked" markers.

I haven't had the time to push these changes into master yet or release a new version on PyPI, but I'll do so as soon as I finish one more round of changes I'm currently working on to support parsing of options in authorized_keys files.

**Comment by nchammas** [comment]
Sounds good. Thanks for the update.

**Comment by ronf** [comment]
This is now fixed in both master and develop, and part of the AsyncSSH 1.0 release (now 1.0.1 due to a bug fix) on PyPI.
