### ISSUE TITLE
Connection with a sentry PDU fails

### ISSUE THREAD

**Issue by xNinjaKittyx** [ronf/asyncssh#192]
Not sure if I'm doing something wrong or something wrong with the library.

With SSH, I connect to a PDU at my work using this command:
`ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -oHostKeyAlgorithms=+ssh-dss user@somefdqn`

Here's what I ran:
```
>>> async def x():
...     async with asyncssh.connect(host='xxxx', username='xxxx', password='xxxx') as f:
...         await f.run('PING')
...
>>> loop.run_until_complete(x())
```

Here's the error:
```
...lib\site-packages\asyncssh\crypto\ec.py:144: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  public_value)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...Python\Python36\Lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "<stdin>", line 2, in x
  File "...lib\site-packages\asyncssh\misc.py", line 186, in __aenter__
    self._result = yield from self._coro
  File "...lib\site-packages\asyncssh\connection.py", line 5454, in connect
    conn, _ = yield from create_connection(None, host, port, **kwargs)
  File "...lib\site-packages\asyncssh\connection.py", line 5110, in create_connection
    yield from auth_waiter
  File "...lib\site-packages\asyncssh\connection.py", line 587, in connection_made
    self._connection_made()
  File "...lib\site-packages\asyncssh\connection.py", line 2248, in _connection_made
    self._peer_addr, port)
  File "...lib\site-packages\asyncssh\connection.py", line 473, in _match_known_hosts
    match_known_hosts(known_hosts, host, addr, port)
  File "...lib\site-packages\asyncssh\known_hosts.py", line 319, in match_known_hosts
    known_hosts = read_known_hosts(known_hosts)
  File "...lib\site-packages\asyncssh\known_hosts.py", line 277, in read_known_hosts
    return import_known_hosts(f.read())
  File "...lib\site-packages\asyncssh\known_hosts.py", line 260, in import_known_hosts
    return SSHKnownHosts(data)
  File "...lib\site-packages\asyncssh\known_hosts.py", line 129, in __init__
    key = import_public_key(data)
  File "...lib\site-packages\asyncssh\public_key.py", line 2626, in import_public_key
    key = decode_ssh_public_key(data)
  File "...lib\site-packages\asyncssh\public_key.py", line 2452, in decode_ssh_public_key
    key = handler.make_public(*key_params)
  File "...lib\site-packages\asyncssh\dsa.py", line 78, in make_public
    return cls(DSAPublicKey.construct(p, q, g, y))
  File "...lib\site-packages\asyncssh\crypto\dsa.py", line 117, in construct
    pub_key = pub.public_key(default_backend())
  File "...lib\site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 206, in public_key
    return backend.load_dsa_public_numbers(self)
  File "...lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 645, in load_dsa_public_numbers
    dsa._check_dsa_parameters(numbers.parameter_numbers)
  File "...lib\site-packages\cryptography\hazmat\primitives\asymmetric\dsa.py", line 132, in _check_dsa_parameters
    raise ValueError("p must be exactly 1024, 2048, or 3072 bits long")
ValueError: p must be exactly 1024, 2048, or 3072 bits long
```

Edit:
asyncssh - 1.15.1
cryptography - 2.5
Python 3.6.5

**Comment by ronf** [comment]
I'm guessing you are using a small DSA key here (perhaps 512 or 768 bits). That's not supported by the PyCA (cryptography) library any more. You might need to generate a larger key, if the device you're talking to will accept that.

Unfortunately, there's nothing I can do in AsyncSSH to disable that restriction. You'd have to talk to the PyCA folks about relaxing that if a larger key is not an option.

Also, from what I remember, there are problems using DSA with SSH with anything larger than a 1024 bit key due to ssh-dss's use of SHA1. So, if you do make a larger key, I would stick with 1024 bits if you stay with DSA. Alternately, you could see if the device supports RSA or ECDSA, which would support stronger keys.

**Comment by xNinjaKittyx** [comment]
Thanks for the response.

Unfortunately this seems like the only option the interface supports, as when trying to do a generic SSH connection, it only asks for a diffie-helman-sha1 with dss host key

I have other methods of connecting with the device outside of SSH, so it's not a big deal.

**Comment by ronf** [comment]
Requiring diffie-hellman-group1-sha1 (or diffie-hellman-group14-sha1) shouldn't be a problem. I think the issue here is with the size of the DSA key on the device (and in the known_hosts file you are using). Would it be possible to assign a 1024-bit DSA key on the device?

**Comment by xNinjaKittyx** [comment]
Interestingly, if I do known_hosts=None, I get a slightly different, but similar error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Python\Python36\Lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "<stdin>", line 2, in x
  File "...\lib\site-packages\asyncssh\misc.py", line 186, in __aenter__
    self._result = yield from self._coro
  File "...\lib\site-packages\asyncssh\connection.py", line 5454, in connect
    conn, _ = yield from create_connection(None, host, port, **kwargs)
  File "...\lib\site-packages\asyncssh\connection.py", line 5110, in create_connection
    yield from auth_waiter
  File "...\lib\site-packages\asyncssh\connection.py", line 627, in data_received
    while self._inpbuf and self._recv_handler():
  File "...\lib\site-packages\asyncssh\connection.py", line 847, in _recv_packet
    processed = handler.process_packet(pkttype, seq, packet)
  File "...\lib\site-packages\asyncssh\packet.py", line 215, in process_packet
    self._packet_handlers[pkttype](self, pkttype, pktid, packet)
  File "...\lib\site-packages\asyncssh\kex_dh.py", line 219, in _process_reply
    host_key = self._conn.validate_server_host_key(host_key_data)
  File "...\lib\site-packages\asyncssh\connection.py", line 2316, in validate_server_host_key
    str(exc)) from None
asyncssh.misc.DisconnectError: Disconnect Error: p must be exactly 1024, 2048, or 3072 bits long
```

As for assigning a DSA key on the device, I'm not 100% sure if it's possible in my context, since I'm not too familiar with what's possible with this device.

**Comment by ronf** [comment]
Ok - this seems to confirm that the server in this case really is providing a key with an unsupported size, and it's not just some other unrelated entry in the known_hosts file that's producing the error. This error is happening during the Diffie-Hellman key exchange, but it's at the point where AsyncSSH is receiving a server host key and trying to use it to verify the Diffie-Hellman reply from the server.

Looking at the cryptography library, the error is originally coming from `_check_dsa_private_numbers()` in cryptography.hazmat.primitives.asymmetric.dsa, and I don't see any way to disable this check (or others like it). Checking the history, it seems that some version of this goes all the way back to the first version of DSA support checked in back in 2014.

If you have control over the device, I'd see if it supports DSA keys of 1024 bits, or better yet RSA keys as there you could potentially use something even longer. I'm guessing the device is older given the key size currently on it, so I doubt it would support ECDSA, but if it did that could also be an option to avoid this problem.
