### ISSUE TITLE
Connection Lost at running command in Alcatel SROS

### ISSUE THREAD

**Issue by dracoboros** [ronf/asyncssh#257]
Hello,

I have the following code:

```python
import asyncio
import asyncssh
import logging


async def main():
    async with asyncssh.connect(
        "198.18.105.55", username="admin", password="admin", known_hosts=None
    ) as conn:
        await conn.run("environment no more", check=True)


logging.basicConfig(level=logging.DEBUG)
asyncio.run(main(), debug=True)
```

The result:
```
DEBUG:asyncio:Using selector: KqueueSelector
INFO:asyncssh:Opening SSH connection to 198.18.105.55, port 22
DEBUG:asyncio:connect <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 0)> to ('198.18.105.55', 22)
DEBUG:asyncio:poll took 11.801 ms: 1 events
INFO:asyncssh:[conn=0] Connection to 198.18.105.55, port 22 succeeded
INFO:asyncssh:[conn=0]   Local address: 198.18.252.1, port 60002
DEBUG:asyncio:<socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('198.18.252.1', 60002), raddr=('198.18.105.55', 22)> connected to 198.18.105.55:22: (<_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>, <asyncssh.connection.SSHClientConnection object at 0x10b5ef510>)
DEBUG:asyncio:poll took 9.363 ms: 1 events
DEBUG:asyncssh:[conn=0] Requesting key exchange
DEBUG:asyncio:poll took 9.760 ms: 1 events
DEBUG:asyncssh:[conn=0] Received key exchange request
DEBUG:asyncssh:[conn=0] Beginning key exchange
DEBUG:asyncio:poll took 11.407 ms: 1 events
DEBUG:asyncio:poll took 17.857 ms: 1 events
DEBUG:asyncssh:[conn=0] Completed key exchange
DEBUG:asyncio:poll took 10.755 ms: 1 events
INFO:asyncssh:[conn=0] Beginning auth for user admin
DEBUG:asyncio:poll took 11.088 ms: 1 events
DEBUG:asyncssh:[conn=0] Received authentication banner
DEBUG:asyncio:poll took 0.011 ms: 1 events
DEBUG:asyncssh:[conn=0] Trying public key auth with ssh-rsa key
DEBUG:asyncio:poll took 11.027 ms: 1 events
DEBUG:asyncssh:[conn=0] Trying password auth
DEBUG:asyncio:poll took 134.869 ms: 1 events
INFO:asyncssh:[conn=0] Auth for user admin succeeded
DEBUG:asyncssh:[conn=0, chan=0] Set write buffer limits: low-water=16384, high-water=65536
INFO:asyncssh:[conn=0, chan=0] Requesting new SSH session
DEBUG:asyncio:poll took 9.418 ms: 1 events
INFO:asyncssh:[conn=0, chan=0]   Command: environment no more
DEBUG:asyncio:poll took 9.554 ms: 1 events
DEBUG:asyncio:<_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>> received EOF
INFO:asyncssh:[conn=0] Connection lost
INFO:asyncssh:[conn=0, chan=0] Closing channel due to connection close
INFO:asyncssh:[conn=0, chan=0] Channel closed: Connection lost
INFO:asyncssh:[conn=0] Closing connection
INFO:asyncssh:[conn=0] Sending disconnect: Disconnected by application (11)
DEBUG:asyncio:Close <_UnixSelectorEventLoop running=False closed=False debug=True>
Traceback (most recent call last):
  File "/Users/dracoboros/Git/project/test.py", line 14, in <module>
    asyncio.run(main(), debug=True)
  File "/Users/dracoboros/.pyenv/versions/3.7.4/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Users/dracoboros/.pyenv/versions/3.7.4/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Users/dracoboros/Git/project/test.py", line 10, in main
    await conn.run("environment no more", check=True)
  File "/Users/dracoboros/.pyenv/versions/project/lib/python3.7/site-packages/asyncssh/connection.py", line 3103, in run
    process = await self.create_process(*args, **kwargs)
  File "/Users/dracoboros/.pyenv/versions/project/lib/python3.7/site-packages/asyncssh/connection.py", line 3009, in create_process
    *args, **kwargs)
  File "/Users/dracoboros/.pyenv/versions/project/lib/python3.7/site-packages/asyncssh/connection.py", line 2927, in create_session
    bool(self._agent_forward_path))
  File "/Users/dracoboros/.pyenv/versions/project/lib/python3.7/site-packages/asyncssh/channel.py", line 1093, in create
    result = await self._make_request(b'exec', String(command))
  File "/Users/dracoboros/.pyenv/versions/project/lib/python3.7/site-packages/asyncssh/channel.py", line 660, in _make_request
    return await waiter
asyncssh.misc.ConnectionLost: Connection lost
```

Every time the `run` function is executed, the connection is lost.

**Comment by ronf** [comment]
This generally means the remote system decided to close the SSH connection on you. Do you have access to the remote system's logs? It looks like you succeeded in completing the SSH handshake and in logging in, but the connect was closed at the TCP level right after sending the command that you are attempting to run.

**Comment by dracoboros** [comment]
I got this:

```
21 2019/07/20 01:07:18.654 UTC MINOR: SECURITY #2009 Base admin
"User admin from 198.18.252.1 logged in"

22 2019/07/20 01:07:18.654 UTC MINOR: USER #2001 Base admin
"User from 198.18.252.1 logged in"

23 2019/07/20 01:07:18.774 UTC MINOR: SECURITY #2010 Base admin
"User admin from 198.18.252.1 logged out"

24 2019/07/20 01:07:18.774 UTC MINOR: USER #2002 Base admin
"User from 198.18.252.1 logged out"
```

Not useful

**Comment by dracoboros** [comment]
Okay, I figured out. When you first logged in SROS, there is a massive banner about the license. Because of that, any command sent to CLI is not entered. I have used the following code to check this:

```python
import asyncio
import asyncssh
import logging


async def main():
    async with asyncssh.connect(
        "198.18.105.55", username="admin", password="admin", known_hosts=None
    ) as conn:
        stdin, stdout, stderr = await conn.open_session()
        out = ""
        while True:
            out += await stdout.read(65535)
            if "R1" in out:
                print(out)
                break


logging.basicConfig(level=logging.DEBUG)
asyncio.run(main(), debug=True)
```

**Comment by ronf** [comment]
If you read the banner as you show here, does it then run the command you sent, or does it still fail whenever you provide a command? I've seen some devices not support sending a command at all, allowing only "shell" style access. You may be running into that here. If that's the case, you should be able to send the command by writing it to stdin (with a newline at the end), possibly after reading the initial banner you mentioned.

**Comment by dracoboros** [comment]
Yeah, @ronf. It is what happened. I will have to take an approach as Netmiko/Netdev libraries did. So asyncssh is running as expected. If there were no further questions, I believe we can close this issue.

**Comment by ronf** [comment]
Sounds good - glad you figured it out. Feel free to open a new issue if you run into other problems!

**Comment by dracoboros** [comment]
Thank you for your support and time, @ronf.
