### ISSUE TITLE
asyncio.wait_for works incorrect for SSHStreamSession._block_read

### ISSUE THREAD

**Issue by fuckthemall** [ronf/asyncssh#31]
When I want to to do consecuitive *readline()* with timeout via *asyncio.wait_for* got exception that stream still blocked. Fragment of example that leads to crash:
```python
        stdin, stdout, stderr = yield from conn.open_session('')

        for op in ['ping 192.168.0.247 -c3', 'ping 192.168.0.2 -c3']:
            stdin.write(op + '\n')

            while not stdout.at_eof():
                try:
                    result = yield from asyncio.wait_for(stdout.readline(), 5)
                    print(op, '=', result, end='')
                except (asyncssh.BreakReceived, asyncssh.SignalReceived, asyncio.TimeoutError):
                    break
                except (asyncssh.TerminalSizeChanged):
                    continue
```

The exception here is:
```
Traceback (most recent call last):
  File "c2.py", line 39, in <module>
    asyncio.get_event_loop().run_until_complete(run_client())
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 268, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 236, in _step
    result = next(coro)
  File "c2.py", line 22, in run_client
    result = yield from asyncio.wait_for(stdout.readline(), 5)
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 371, in wait_for
    return fut.result()
  File "/usr/lib64/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 236, in _step
    result = next(coro)
  File "~/venv3/lib/python3.4/site-packages/asyncssh/stream.py", line 385, in readline
    yield from self._block_read(datatype)
  File "~/venv3/lib/python3.4/site-packages/asyncssh/stream.py", line 219, in _block_read
    raise RuntimeError('read called while another coroutine is '
RuntimeError: read called while another coroutine is already waiting to read
```

So if on the first try *asyncio.wait_for* generate *asyncio.TimeoutError* the SSHStreamSession._read_waiter still has the cancelled Task that leads to this exception.

Environment:
OS: Fedora 22 x86_64
Python 3.4.2 (default, Jul 9 2015, 17:24:30) 
AsyncSSH 1.3.0

For me was ok just do *SSHStreamSession._unblock_read* for the case if Task with *_block_read* was cancelled (see the 795a6f6918e417e37f83c6dfdecb394a6836ef41).

**Comment by ronf** [comment]
Thanks for reporting this. Could you give the following patch a try?

```patch
diff --git a/asyncssh/stream.py b/asyncssh/stream.py
index 00d80a2..2b6f309 100644
--- a/asyncssh/stream.py
+++ b/asyncssh/stream.py
@@ -219,9 +219,12 @@ class SSHStreamSession:
             raise RuntimeError('read called while another coroutine is '
                                'already waiting to read')
 
-        waiter = asyncio.Future(loop=self._loop)
-        self._read_waiter[datatype] = waiter
-        yield from waiter
+        try:
+            waiter = asyncio.Future(loop=self._loop)
+            self._read_waiter[datatype] = waiter
+            yield from waiter
+        finally:
+            self._read_waiter[datatype] = None
 
     def _unblock_read(self, datatype):
         """Signal that more data has arrived on the stream"""
@@ -230,7 +233,6 @@ class SSHStreamSession:
         if waiter:
             if not waiter.cancelled():
                 waiter.set_result(None)
-            self._read_waiter[datatype] = None
 
     def _unblock_drain(self):
         """Signal that more data can be written on the stream"""
```

**Comment by fuckthemall** [comment]
Thanks for the provided patch. Tests with this patch shows expected behavior, i.e. readline() works after an asyncio.TimeoutError exception.

**Comment by ronf** [comment]
Terrific - this change is now checked into develop, and I'm working on making similar changes in a few other places where this pattern is used.
