### ISSUE TITLE
Example crashing with Python 3.4

### ISSUE THREAD

**Issue by aproano2** [ronf/asyncssh#32]
I was trying to run the example that echoes "Hello", and found errors in python 3.4 in mac os

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 93, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 218, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 941, in call_exception_handler
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 1303, in error
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 1409, in _log
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 1419, in handle
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 1489, in callHandlers
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 853, in handle
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 984, in emit
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 906, in handleError
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py", line 169, in print_exception
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py", line 153, in _format_exception_iter
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py", line 18, in _format_list_iter
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py", line 65, in _extract_tb_or_stack_iter
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py", line 15, in getline
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py", line 41, in getlines
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py", line 126, in updatecache
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py", line 437, in open
AttributeError: 'module' object has no attribute 'open'

**Comment by ronf** [comment]
I think something in corrupted in your Python 3.4 install. The proper version of the tokenize.py module in Python 3.4 definitely has an open() function, and everything else in your traceback is from standard Python library calls, so I don't even think you are getting far enough to get into the AsyncSSH code.
