### ISSUE TITLE
'Unexpected FX_OK' after SFTP connection closed

### ISSUE THREAD

**Issue by phaxx** [ronf/asyncssh#345]
Hi, 

I have a rather simple client connects to an SFTP location and downloads all the files:

```
async def run_client():
    async with asyncssh.connect(
        "<<hostname>>",
        port=22,
        username="<<username>>",
        password="<<pwd>>,
        keepalive_interval=60,
        known_hosts=None,
    ) as conn:
        path = "/"
        async with conn.start_sftp_client() as sftp:
            files = await sftp.listdir(path)
            for file_name in files:
                file_path = "{}{}".format(path, file_name)
                file_with_processed_path = "{}Processed/{}".format(path, file_name)
                logging.info(file_with_processed_path)
                logging.info("Downloading {}".format(file_name))
                async with sftp.open(file_path, "rb") as file:
                    file_content = await file.read()
                    file.write(file_content)
```

When looking at the logs, seems like the client connects fine, lists files, downloads them, then closes connection. After that the exception happens. Here's last couple of lines of logs + stack trace:

```
2021-02-04 11:30:21,749 - asyncssh.sftp - DEBUG - [conn=0, chan=0] Received OK
2021-02-04 11:30:21,749 - asyncssh.sftp - DEBUG - [conn=0, chan=0] Sending close for handle 687832
2021-02-04 11:30:21,837 - asyncssh.sftp - DEBUG - [conn=0, chan=0] Received OK
2021-02-04 11:30:21,926 - asyncssh - INFO - [conn=0, chan=0] Received exit status 0
2021-02-04 11:30:22,051 - asyncssh - INFO - [conn=0, chan=0] Received channel close
2021-02-04 11:30:22,052 - asyncssh.sftp - INFO - [conn=0, chan=0] SFTP client exited
2021-02-04 11:30:22,052 - asyncssh - INFO - [conn=0, chan=0] Closing channel
2021-02-04 11:30:22,052 - asyncssh - INFO - [conn=0, chan=0] Channel closed
2021-02-04 11:30:22,052 - asyncssh - INFO - [conn=0] Closing connection
2021-02-04 11:30:22,052 - asyncssh - INFO - [conn=0] Sending disconnect: Disconnected by application (11)
2021-02-04 11:30:22,053 - asyncssh - INFO - [conn=0] Connection closed
Traceback (most recent call last):
  File "<string>", line 38, in <module>
  File "<string>", line 36, in __run
  File "<<omit>>/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "<<omit>>/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "<<omit>>login_test#link-tree/<<omit>>login_test.py", line 88, in <module>
    asyncio.get_event_loop().run_until_complete(run_client())
  File "<<omit>>python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "<<omit>>/login_test#link-tree/<<omit>>login_test.py", line 76, in run_client
    file_content = await file.read()
  File "<<omit>>#link-tree/asyncssh/sftp.py", line 1664, in read
    size = (await self._end()) - offset
  File "<<omit>>#link-tree/asyncssh/sftp.py", line 1613, in _end
    attrs = await self.stat()
  File "<<omit>>#link-tree/asyncssh/sftp.py", line 1799, in stat
    return await self._handler.fstat(self._handle)
  File "<<omit>>#link-tree/asyncssh/sftp.py", line 1407, in fstat
    return await self._make_request(FXP_FSTAT, String(handle))
  File "<<omit>>#link-tree/asyncssh/sftp.py", line 1194, in _make_request
    raise SFTPBadMessage('Unexpected FX_OK response')
asyncssh.sftp.SFTPBadMessage: Unexpected FX_OK response
```

The `result` and `return_type` variables in `_make_request` are in fact `None` and `105` respectively when the exception is thrown. The server works fine with any other SFTP client. I'm wondering why `asyncssh` is still listening after allegedly closing the connection. Is this expected or is the server code wrong?

**Comment by ronf** [comment]
I see you closed this already - were you able to figure out the problem?

It looks to me like there was still a request outstanding at the time you closed the connection, and so it is attempt to wake up that coroutine to let it know the connection closed. If I'm right about that, the error is definitely misleading, but I would expect some form of exception to be thrown in that case to let the caller know the request didn't complete before the connection was closed.

**Comment by phaxx** [comment]
Hi Ron,

I rewrote the client code not to use context manager but just use `await sftp.get(...)` and that fixed it.

**Comment by ronf** [comment]
Interesting. I would expect either of these to work.

I'm glad you have it working now. That said, if you feel like creating a test case that reproduces the problem I'd be happy to take a closer look.
