### ISSUE TITLE
TimeoutError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by mihaimyh** [ronf/asyncssh#360]
Hi,

I am getting connection timed out when running some SSH commands, some of them might be long running commands:

```
Fatal read error on socket transport
protocol: <asyncssh.connection.SSHClientConnection object at 0x7fc3402ee278>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
Traceback (most recent call last):
  File "/opt/sdl_uac_ops/bin/post_fw_ssh_exec", line 178, in <module>
    exit_status = ssh_execute_with_config(config, arg.args, sshconfiglabel)
  File "/opt/sdl_uac_ops/bin/post_fw_ssh_exec", line 87, in ssh_execute_with_config
    command=command))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/opt/sdl_uac_ops/lib64/python3.6/site-packages/sdl_uac_ops_tools/SSHAsync.py", line 9, in execute_command
    async for line in process.stdout:
  File "/opt/sdl_uac_ops/lib64/python3.6/site-packages/asyncssh/stream.py", line 50, in __aiter__
    yield await self.readline()
  File "/opt/sdl_uac_ops/lib64/python3.6/site-packages/asyncssh/stream.py", line 144, in readline
    return await self.readuntil(_NEWLINE)
  File "/opt/sdl_uac_ops/lib64/python3.6/site-packages/asyncssh/stream.py", line 170, in readuntil
    return await self._session.readuntil(separator, self._datatype)
  File "/opt/sdl_uac_ops/lib64/python3.6/site-packages/asyncssh/stream.py", line 550, in readuntil
    raise exc
  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out

```

This is how I am running the commands:

```
import asyncssh
from loguru import logger


async def execute_command(host, username, private_key_file, command, port: int = 22):
    async with asyncssh.connect(host, port, username=username, client_keys=[private_key_file],
                                known_hosts=None) as conn:
        async with conn.create_process(command) as process:
            async for line in process.stdout:
                if line:
                    logger.debug(repr(line))
            async for err in process.stderr:
                if err:
                    logger.error(repr(err))
            if process.exit_status == 0:
                logger.info('Command {} finished successfully.', command)
            else:
                logger.error('Command {} finished unsuccessfully.', command)

            return process.exit_status

```

Anyone encountered this before?

**Comment by ronf** [comment]
You may be running into https://stackoverflow.com/questions/16772519/socket-recv-on-selected-socket-failing-with-etimedout/38792437. According to that page, you can get a TimeoutError from a TCP keepalive failure, which can happen if connectivity is lost on a long running connection, perhaps because some of something like a firewall or NAT device losing state.

You can try enabling the SSH-level keep alive by setting the keepalive_interval argument on your connect() call. Something like 60 seconds would be a reasonable value, which can be expressed as either the integer 60 or as a string with units such as '1m' (1 minute). This will make sure there's regular traffic flowing on the connection to prevent intermediate devices from aging out the connection state. If the connection fails for some other reason, it will also detect that failure more quickly.

**Comment by mihaimyh** [comment]
@ronf I tried your suggestion, now I get a ConnectionLost exception:

```
Traceback (most recent call last):
  File "/opt/sdl_uac_ops/bin/post_fw_ssh_exec", line 178, in <module>
    exit_status = ssh_execute_with_config(config, arg.args, sshconfiglabel)
  File "/opt/sdl_uac_ops/bin/post_fw_ssh_exec", line 87, in ssh_execute_with_config
    command=command))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/opt/sdl_uac_ops/lib64/python3.6/site-packages/sdl_uac_ops_tools/SSHAsync.py", line 7, in execute_command
    known_hosts=None, keepalive_interval=60) as conn:
  File "/opt/sdl_uac_ops/lib64/python3.6/site-packages/asyncssh/misc.py", line 220, in __aenter__
    self._result = await self._coro
  File "/opt/sdl_uac_ops/lib64/python3.6/site-packages/asyncssh/connection.py", line 6462, in connect
    conn_factory, 'Opening SSH connection to')
  File "/opt/sdl_uac_ops/lib64/python3.6/site-packages/asyncssh/connection.py", line 223, in _connect
    await conn.wait_established()
  File "/opt/sdl_uac_ops/lib64/python3.6/site-packages/asyncssh/connection.py", line 2107, in wait_established
    await self._waiter
asyncssh.misc.ConnectionLost: Connection lost
```

**Comment by ronf** [comment]
The new error you are getting seems to be related to trying to connect to a host and port that's not listening for connections. This is completely different from what you were seeing before, where the connect succeeded but later you got an error while calling readline().

**Comment by mihaimyh** [comment]
Thanks for the answer, but actually the host and the port are correct. This script is being called in a loop and one instance of it failed with the above error.

**Comment by ronf** [comment]
If you are getting connection failures, you may be opening connections too quickly. Most SSH servers limit the rate at which connections come in, or limit the number of simultaneous connections allowed which haven't finished authenticating yet (see MaxStartups in OpenSSH, for instance).

**Comment by ronf** [comment]
Closing due to inactivity. Please open a new issue if you have additional questions.

**Comment by Kellyyesenia** [comment]
Hola me sale este error estoy usando ubuntu 24.04

add-apt-repository ppa:ondrej/php -y
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 452, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 435, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 89, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 133, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 111, in lp
    self._lp = login_func("%s.%s" % (self.__module__, self.__class__.__name__),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously
    return cls(
           ^^^^
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in __init__
    super(Launchpad, self).__init__(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 511, in __init__
    self._wadl = self._browser.get_wadl_application(self._root_uri)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 502, in get_wadl_application
    response, content = self._request(url, media_type=wadl_type)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 441, in _request
    response, content = self._request_and_retry(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 400, in _request_and_retry
    response, content = self._connection.request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1701, in request
    (response, content) = self._request(
                          ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 144, in _request
    response, content = super(LaunchpadOAuthAwareHttp, self)._request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 204, in _request
    return super(RestfulHttp, self)._request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1421, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1343, in _conn_request
    conn.connect()
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1133, in connect
    sock.connect((self.host, self.port))
TimeoutError: [Errno 110] Connection timed out

**Comment by ronf** [comment]
Sorry, but I think you posted this to the wrong place. I don't see any sign of AsyncSSH being used here by "/usr/bin/add-apt-repository".

The error seems to be when trying to make an outbound TCP connection when attempting to make an HTTP request from httplib2.

**Comment by PedroPPM** [comment]
@Kellyyesenia conseguiu resolver?

**Comment by ronf** [comment]
As I said, this error appears to be coming from httplib2, which has nothing to do with AsyncSSH, so I don't think this is the right place for your question.
