### ISSUE TITLE
CancelledError during auth when trying asyncssh.connect on Centos 8.3 machine

### ISSUE THREAD

**Issue by melissa-kun-li** [ronf/asyncssh#392]
Hi Ron, I was wondering if you could help me with this issue I've been having. I'm trying to integrate your library into a project, and it works well on ubuntu 20.04 and centos 8.2, but it's not working on centos 8.3 machines. The centos 8.3 machines have the same error shown below. Would you have any ideas as to why this error is occurring?

This is what I'm seeing in the program log:

```
2021-08-04T15:45:47.178+0000 7f1acfd8b700 -1 log_channel(cephadm) log [ERR] : 
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/cephadm/ssh.py", line 98, in redirect_log
    yield
  File "/usr/share/ceph/mgr/cephadm/ssh.py", line 77, in _remote_connection
    conn = await asyncssh.connect(addr, username=self.mgr.ssh_user, client_keys=[self.mgr.tkey.name], known_hosts=None, server_host_key_algs=['ssh-rsa'], config=[self.mgr.ssh_config_fname])
  File "/lib64/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/lib/python3.6/site-packages/asyncssh/connection.py", line 6804, in connect
    'Opening SSH connection to')
  File "/lib64/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/lib/python3.6/site-packages/asyncssh/connection.py", line 303, in _connect
    await conn.wait_established()
  File "/lib64/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/lib/python3.6/site-packages/asyncssh/connection.py", line 2243, in wait_established
    await self._waiter
  File "/lib/python3.6/site-packages/asyncssh/connection.py", line 829, in _reap_task
    task.result()
concurrent.futures._base.CancelledError
2021-08-04T15:45:47.178+0000 7f1af7ed7700 20 mgr dispatch_remote Success calling 'apply'
2021-08-04T15:45:47.178+0000 7f1af7ed7700 20 mgr ~Gil Destroying new thread state 0x55c41f76fb00
2021-08-04T15:45:47.178+0000 7f1af7ed7700 20 mgr ~Gil Destroying new thread state 0x55c41f2fbb00
2021-08-04T15:45:47.178+0000 7f1af7ed7700 -1 mgr.server reply reply (22) Invalid argument Failed to connect to smithi198 (<IP>): CancelledError()
Log: Opening SSH connection to <IP>, port 22
[conn=0] Connected to SSH server at <IP>, port 22
[conn=0]   Local address: <IP>, port 49630
[conn=0]   Peer address: <IP>, port 22
[conn=0] Sending version SSH-2.0-AsyncSSH_2.7.0
[conn=0] Received version SSH-2.0-OpenSSH_8.0
[conn=0] Requesting key exchange
[conn=0]   Key exchange algs: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,ecdh-sha2-1.3.132.0.10,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256@ssh.com,diffie-hellman-group14-sha1,rsa2048-sha256
[conn=0]   Host key algs: ssh-rsa
[conn=0]   Encryption algs: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
[conn=0]   MAC algs: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha256-2@ssh.com,hmac-sha224@ssh.com,hmac-sha256@ssh.com,hmac-sha384@ssh.com,hmac-sha512@ssh.com
[conn=0]   Compression algs: zlib@openssh.com,none
[conn=0] Received key exchange request
[conn=0]   Key exchange algs: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1
[conn=0]   Host key algs: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256
[conn=0]   Client to server:
[conn=0]     Encryption algs: aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes256-cbc,aes128-gcm@openssh.com,aes128-ctr,aes128-cbc
[conn=0]     MAC algs: hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512
[conn=0]     Compression algs: none,zlib@openssh.com
[conn=0]   Server to client:
[conn=0]     Encryption algs: aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes256-cbc,aes128-gcm@openssh.com,aes128-ctr,aes128-cbc
[conn=0]     MAC algs: hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512
[conn=0]     Compression algs: none,zlib@openssh.com
[conn=0] Beginning key exchange
[conn=0]   Key exchange alg: curve25519-sha256
[conn=0]   Client to server:
[conn=0]     Encryption alg: chacha20-poly1305@openssh.com
[conn=0]     MAC alg: chacha20-poly1305@openssh.com
[conn=0]     Compression alg: zlib@openssh.com
[conn=0]   Server to client:
[conn=0]     Encryption alg: chacha20-poly1305@openssh.com
[conn=0]     MAC alg: chacha20-poly1305@openssh.com
[conn=0]     Compression alg: zlib@openssh.com
[conn=0] Requesting service ssh-userauth
[conn=0] Completed key exchange
[conn=0] Received extension info
[conn=0]   server-sig-algs: ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[conn=0] Request for service ssh-userauth accepted
[conn=0] Beginning auth for user root
[conn=0] Remaining auth methods: publickey,gssapi-keyex,gssapi-with-mic,password
[conn=0] Preferred auth methods: gssapi-keyex,gssapi-with-mic,hostbased,publickey,keyboard-interactive,password
[conn=0] Uncaught exception
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/asyncssh/connection.py", line 829, in _reap_task
    task.result()
concurrent.futures._base.CancelledError
[conn=0] Trying public key auth with rsa-sha2-256 key
[conn=0] Uncaught exception
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/asyncssh/connection.py", line 829, in _reap_task
    task.result()
concurrent.futures._base.CancelledError
[conn=0] Connection failure: 
[conn=0] Aborting connection
```

**Comment by ronf** [comment]
Hi Melissa,

Unfortunately, there isn't much to go on here. If you have it working on CentOS 8.2, you might try comparing the logs in the working case vs. the non-working one to look to see how they differ. You might also want to turn up the debug level to 3 to see exactly which packet you receive right before getting the exception.

There are multiple places where an async auth task can be cancelled, but generally it would happen when the remote system either closes the connection or when it sends a message indicating auth has completed (either successfully, or after a failure) and it is trying to move on. If there's still an auth task outstanding, AsyncSSH will try to clean it up using cancel().

I noticed that gssapi-keyex is listed as a preferred auth method -- are you trying to use a GSSAPI-based auth method? If you remove that, do you still see a problem?

**Comment by melissa-kun-li** [comment]
Hi Ron,

Thanks for your reply and suggestion! It took me a while to get access to the machine and environment the failure was on, but I tried out your suggestion of disabling GSSAPI (commented out GSSAPIAuthentication yes, set GSSAPIAuthentication no, commented out GSSAPICleanupCredentials yes) in the ssh_config and sshd_config of a RHEL 8.3 machine..... and it worked! Will try again on the other machines and see if it also works. 

I'm not familiar with GSSAPI, and not sure what was specifically causing the failure as the same ssh_config and sshd_config works on Centos 8.2, but when I compared the sshd logs between the one with GSSAPIAuthentication enabled (fails) and the one without (succeeds), I see there is a difference here after `send packet: type 51 [preauth]`:

```
Aug 18 20:44:35 smithi106 sshd[26433]: debug3: userauth_finish: failure partial=0 next methods="publickey,gssapi-keyex,gssapi-with-mic,password" [preauth]
Aug 18 20:44:35 smithi106 sshd[26433]: debug3: send packet: type 51 [preauth]
Aug 18 20:44:35 smithi106 sshd[26433]: debug3: mm_request_send entering: type 122 [preauth]
Aug 18 20:44:35 smithi106 sshd[26433]: debug3: mm_request_receive_expect entering: type 123 [preauth]
Aug 18 20:44:35 smithi106 sshd[26433]: debug3: mm_request_receive entering [preauth]
Aug 18 20:44:35 smithi106 sshd[26433]: debug3: mm_request_receive entering
Aug 18 20:44:35 smithi106 sshd[26433]: debug3: monitor_read: checking request 122
Aug 18 20:44:35 smithi106 sshd[26433]: debug3: mm_request_send entering: type 123
Aug 18 20:44:35 smithi106 sshd[26433]: Connection closed by authenticating user root <IP> port 43936 [preauth]
... (fails)
```

```
Aug 18 21:56:33 smithi106 sshd[24487]: debug3: send packet: type 51 [preauth]
Aug 18 21:56:33 smithi106 sshd[24487]: debug3: receive packet: type 2 [preauth]
Aug 18 21:56:33 smithi106 sshd[24487]: debug3: Received SSH2_MSG_IGNORE [preauth]
Aug 18 21:56:33 smithi106 sshd[24487]: debug3: receive packet: type 50 [preauth]
Aug 18 21:56:33 smithi106 sshd[24487]: debug1: userauth-request for user root service ssh-connection method publickey [preauth]
Aug 18 21:56:33 smithi106 sshd[24487]: debug1: attempt 1 failures 0 [preauth]
Aug 18 21:56:33 smithi106 sshd[24487]: debug2: input_userauth_request: try method publickey [preauth]
... (succeeds)
```
Other than the `Connection closed by authenticating user` I couldn't see any explicit errors.
Anyways, thanks again for your help Ron :D

**Comment by ronf** [comment]
Glad to hear you got it working, Melissa!

If you feel like debugging this further (up to you!), here are some additional thoughts about things to try:

GSSAPI would normally be used for Kerberos authentication. Do you know if that's set up on the client and server machines you are using? If you run "klist" from the shell where you're running the process that calls AsyncSSH, do you see anything listed?

I see you captured the server side debug logs, but do you have AsyncSSH debug logs at level 3, showing the individual packets being sent/received? From the OpenSSH log, I can't quite tell what is being sent just after the userauth failure. My guess is that AsyncSSH is trying to initiate GSS authentication and something is going wrong, but I'm not sure what specifically.

Note: If you do grab the level 3 logs, you'll want to check them over to scrub out any sensitive information. It doesn't look like you're doing password auth here, so you should be ok on that front, but if you need to remove anything just let me know (like you did here with placeholders for some items). It just gets a bit more involved because there are hex dumps of the raw packets. We can also take this to e-mail if you'd prefer that to posting the info publicly here.

**Comment by melissa-kun-li** [comment]
Thanks Ron, sent an email!
