### ISSUE TITLE
Cannot run simple client

### ISSUE THREAD

**Issue by RonDingDing** [ronf/asyncssh#418]
This doesn't run at all.

```python
import asyncio, asyncssh, sys

async def run_client():
    async with asyncssh.connect('192.168.1.2', username="root", password="password", port=22) as conn:
        result = await conn.run('ls /', check=True)
        print(result.stdout, end='')

asyncio.get_event_loop().run_until_complete(run_client())
```

```python
  File "D:\Working\venv\lib\site-packages\asyncssh\misc.py", line 220, in __aenter__
    self._result = await self._coro
  File "D:\Working\venv\lib\site-packages\asyncssh\connection.py", line 6855, in connect
    return await _connect(options, loop, flags, conn_factory,
  File "D:\Working\venv\lib\site-packages\asyncssh\connection.py", line 303, in _connect
    await conn.wait_established()
  File "D:\Working\venv\lib\site-packages\asyncssh\connection.py", line 2262, in wait_established        
    await self._waiter
asyncssh.misc.ConnectionLost: Connection lost
```

**Comment by ronf** [comment]
Usually that indicates a problem on the server side, where it doesn't like something sent in the handshake. If you connect to a different host (preferably with a different version of SSH), do you still see the problem?

To get a feel for where in the handshake it is failing, you can turn on debugging with something like:

```python
    import logging
    logging.basicConfig(level='DEBUG')
    asyncssh.set_debug_level(2)
```

If you have access to the server's SSH logs, you might also want to look to see if anything is showing up there.

**Comment by RonDingDing** [comment]
```
DEBUG:asyncio:Using proactor: IocpProactor
INFO:asyncssh:Opening SSH connection to 192.168.1.192, port 22
INFO:asyncssh:[conn=0] Connected to SSH server at 192.168.1.192, port 22
INFO:asyncssh:[conn=0]   Local address: 192.168.1.18, port 18234
INFO:asyncssh:[conn=0]   Peer address: 192.168.1.192, port 22
DEBUG:asyncssh:[conn=0] Sending version SSH-2.0-AsyncSSH_2.7.2
DEBUG:asyncssh:[conn=0] Received version SSH-2.0-OpenSSH_6.3
DEBUG:asyncssh:[conn=0] Requesting key exchange
DEBUG:asyncssh:[conn=0]   Key exchange algs: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,ecdh-sha2-1.3.132.0.10,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256@ssh.com,diffie-hellman-group14-sha1,rsa2048-sha256,ext-info-c
DEBUG:asyncssh:[conn=0]   Host key algs: rsa-sha2-256,rsa-sha2-512,ssh-rsa-sha224@ssh.com,ssh-rsa-sha256@ssh.com,ssh-rsa-sha384@ssh.com,ssh-rsa-sha512@ssh.com,ssh-rsa
DEBUG:asyncssh:[conn=0]   Encryption algs: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
DEBUG:asyncssh:[conn=0]   MAC algs: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha256-2@ssh.com,hmac-sha224@ssh.com,hmac-sha256@ssh.com,hmac-sha384@ssh.com,hmac-sha512@ssh.comDEBUG:asyncssh:[conn=0]   Compression algs: zlib@openssh.com,none
DEBUG:asyncssh:[conn=0] Received key exchange request
DEBUG:asyncssh:[conn=0]   Key exchange algs: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG:asyncssh:[conn=0]   Host key algs: ssh-rsa
DEBUG:asyncssh:[conn=0]   Client to server:
DEBUG:asyncssh:[conn=0]     Encryption algs: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
DEBUG:asyncssh:[conn=0]     MAC algs: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
DEBUG:asyncssh:[conn=0]     Compression algs: none,zlib@openssh.com
DEBUG:asyncssh:[conn=0]   Server to client:
DEBUG:asyncssh:[conn=0]     Encryption algs: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
DEBUG:asyncssh:[conn=0]     MAC algs: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
DEBUG:asyncssh:[conn=0]     Compression algs: none,zlib@openssh.com
DEBUG:asyncssh:[conn=0] Beginning key exchange
DEBUG:asyncssh:[conn=0]   Key exchange alg: ecdh-sha2-nistp521
INFO:asyncssh:[conn=0] Connection lost
INFO:asyncssh:[conn=0] Aborting connection
Traceback (most recent call last):
  File "c:\Users\XenaDev\Desktop\playground.py", line 12, in <module>
    asyncio.get_event_loop().run_until_complete(run_client())
  File "D:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\Users\XenaDev\Desktop\playground.py", line 8, in run_client
    async with asyncssh.connect('192.168.1.192', username="root", password="rodebutik", port=22) as conn:
  File "d:\Working\venv\lib\site-packages\asyncssh\misc.py", line 220, in __aenter__
    self._result = await self._coro
  File "d:\Working\venv\lib\site-packages\asyncssh\connection.py", line 6855, in connect
    return await _connect(options, loop, flags, conn_factory,
  File "d:\Working\venv\lib\site-packages\asyncssh\connection.py", line 303, in _connect
    await conn.wait_established()
  File "d:\Working\venv\lib\site-packages\asyncssh\connection.py", line 2262, in wait_established
    await self._waiter
asyncssh.misc.ConnectionLost: Connection lost

```

**Comment by RonDingDing** [comment]
But I tested it with paramiko based ssh client and it works fine.

**Comment by ronf** [comment]
Do you have access to the logs on the server? It's running a VERY old version of OpenSSH (6.3, which came out back in 2013), and it looks like it is dropping the connection before completing the SSH handshake.

With other SSH servers, I've seen problem in some cases there being a limit on the number of algorithms they allow you to advertise. With AsyncSSH supporting so many different algorithms, it sometimes exceeds the length of the list the SSH server allows. If you explicitly request a particular algorithm (or provide a shorter list of values to choose from), it can work around whatever limit exists on the server in these cases.

Looking at the advertised algorithms on each side, it looks like there is an overlap. When you run paramiko, which key exchange and encryption algorithms get chosen? If you ask for those explicitly in AsyncSSH, does that fix the problem?

**Comment by RonDingDing** [comment]
I just use default at everything with paramiko~

**Comment by RonDingDing** [comment]
The thing I know is the system is a fedora 2013 version. You can try to get one and find what's wrong.
```
[root@localhost ~]# cat /etc/issue
Fedora release 20 (Heisenbug)
Kernel \r on an \m (\l)      

[root@localhost ~]# openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013

[root@localhost ~]# ssh -V
OpenSSH_6.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013
```

**Comment by ronf** [comment]
I experimented a bit with a Fedora 20 system tonight. I can't explain _why_ OpenSSH 6.3p1 is behaving the way it is, but the problem appears to be related to the key exchange algorithms being sent. By default, AsyncSSH will send:

curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,ecdh-sha2-1.3.132.0.10,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256@ssh.com,diffie-hellman-group14-sha1,rsa2048-sha256,ext-info-c

and OpenSSH 6.3p1 will send:

ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

AsyncSSH does support the ecdh algorithms listed at the beginning of the OpenSSH 6.3 list, but when AsyncSSH sends the other algorithms first OpenSSH fails to find a match and exits without completing the handshake. If you add the argument `kex_algs='ecdh-sha2-nistp256'` in the AsyncSSH connect() call, this seems to work around the problem, at least in my testing here.

I also noticed that Fedora 20 only creates an ssh-rsa host key by default. This isn't a problem for AsyncSSH, but the latest OpenSSH doesn't accept ssh-rsa host keys any more (at least not be default). So, you end up having to add ssh-rsa to the list of supported HostKeyAlgorithms to be able to log in with that.

I'm running into other incompatibilities which seem to be causing the SSH connection to fail later during or just after authentication, but you might want to try adding the `kex_algs` argument I mention above and see if it helps you.

**Comment by ronf** [comment]
Experimenting with this a bit more, it seems that the SSH on Fedora 20 doesn't like the "ecdh-sha2-nistp521" algorithm, even though it advertises it. If I disable that in AsyncSSH, the key exchange works (selecting "ecdh-sha2-nistp384"). Explicitly setting AsyncSSH to only advertise "ecdh-sha2-nistp256" also works, as noted above.

Based on a Google search, I see other complaints about 521-bit EC keys not working on Fedora 20. Apparently RedHat disabled a number of curves in OpenSSL by default, but OpenSSH was not changed to avoid using some of the disabled key types.

So, I think the "bug" is on the Fedora 20 version of OpenSSH, but you can work around it in AsyncSSH by not using algorithms that involve 521-bit EC keys, or by changing the order to advertise the other key sizes first.

**Comment by ronf** [comment]
Closing due to inactivity. If you're still having problems, feel free to re-open this or create a new issue.
