### ISSUE TITLE
2.8.0 - Passphrase no longer working

### ISSUE THREAD

**Issue by Ch3LL** [ronf/asyncssh#419]
I am seeing this error:

```
(heist)  ch3ll@megan-precision5550  ~/git/asyncssh  ➦ 402154b <B>  python ~/test.py
Traceback (most recent call last):
  File "/home/ch3ll/test.py", line 14, in <module>
    loop.run_until_complete(test_connection())
  File "/home/ch3ll/.pyenv/versions/3.8.6/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ch3ll/test.py", line 10, in test_connection
    await asyncssh.connect(id_, **con_opts)
  File "/home/ch3ll/git/asyncssh/asyncssh/connection.py", line 6887, in connect
    options = SSHClientConnectionOptions(options, config=config, host=host,
  File "/home/ch3ll/git/asyncssh/asyncssh/connection.py", line 5596, in __init__
    super().__init__(options=options, last_config=last_config, **kwargs)
  File "/home/ch3ll/git/asyncssh/asyncssh/misc.py", line 271, in __init__
    self.prepare(**self.kwargs)
  File "/home/ch3ll/git/asyncssh/asyncssh/connection.py", line 6328, in prepare
    self.client_keys = load_keypairs(client_keys, passphrase,
  File "/home/ch3ll/git/asyncssh/asyncssh/public_key.py", line 3152, in load_keypairs
    key, certs = read_private_key_and_certs(key, passphrase)
  File "/home/ch3ll/git/asyncssh/asyncssh/public_key.py", line 2969, in read_private_key_and_certs
    key, cert = import_private_key_and_certs(read_file(filename), passphrase)
  File "/home/ch3ll/git/asyncssh/asyncssh/public_key.py", line 2859, in import_private_key_and_certs
    key, end = _decode_private(data, passphrase)
  File "/home/ch3ll/git/asyncssh/asyncssh/public_key.py", line 2519, in _decode_private
    key = _decode_pem_private(pem_name, headers, data, passphrase)
  File "/home/ch3ll/git/asyncssh/asyncssh/public_key.py", line 2433, in _decode_pem_private
    return _decode_openssh_private(data, passphrase)
  File "/home/ch3ll/git/asyncssh/asyncssh/public_key.py", line 2276, in _decode_openssh_private
    raise KeyImportError('Passphrase must be specified to import '
asyncssh.public_key.KeyImportError: Passphrase must be specified to import encrypted private keys
```

When using `passphrase`.  Here is a snippet of what I'm trying to do:

```
import asyncio
import asyncssh

id_ = "192.168.1.16"
con_opts = {'known_hosts': None, 'username': 'root', 'client_keys':
            ['/home/ch3ll/.ssh/id_rsa'], 'passphrase': 'password',
            'config': '/etc/heist/heist.conf'}

async def test_connection():
    await asyncssh.connect(id_, **con_opts)

loop = asyncio.get_event_loop()
try:
    loop.run_until_complete(test_connection())
except (OSError, asyncssh.Error) as exc:
    sys.exit(f"Error starting server: {exc}")
```

Git bisect shows this commit:
16becd851f5ca413e5033f17512a962e9a1e9581

This patch fixes the issue for me:

```
diff --git a/asyncssh/connection.py b/asyncssh/connection.py
index 9419718..454bb48 100644
--- a/asyncssh/connection.py
+++ b/asyncssh/connection.py
@@ -5591,9 +5591,10 @@ class SSHServerConnection(SSHConnection):
 class SSHConnectionOptions(Options):
     """SSH connection options"""
 
-    def __init__(self, options=None, **kwargs):
+    def __init__(self, options=None, passphrase=None, **kwargs):
         last_config = options.config if options else None
-        super().__init__(options=options, last_config=last_config, **kwargs)
+        super().__init__(options=options, last_config=last_config,
+                         passphrase=passphrase, **kwargs)
 
     # pylint: disable=arguments-differ
     def prepare(self, config, protocol_factory, version, host, port, tunnel,
@@ -6887,6 +6888,7 @@ async def connect(host, port=(), *, tunnel=(), family=(), flags=0,
     options = SSHClientConnectionOptions(options, config=config, host=host,
                                          port=port, tunnel=tunnel,
                                          family=family, local_addr=local_addr,
+                                         passphrase=passphrase,
                                          **kwargs)
 
     return await asyncio.wait_for(
diff --git a/asyncssh/misc.py b/asyncssh/misc.py
index 9e7527f..ce0fa13 100644
--- a/asyncssh/misc.py
+++ b/asyncssh/misc.py
@@ -257,7 +257,7 @@ async def maybe_wait_closed(writer):
 class Options:
     """Container for configuration options"""
 
-    def __init__(self, options=None, **kwargs):
+    def __init__(self, options=None, passphrase=None, **kwargs):
         if options:
             if not isinstance(options, type(self)):
                 raise TypeError('Invalid %s, got %s' %
@@ -268,7 +268,7 @@ class Options:
             self.kwargs = {}
 
         self.kwargs.update(kwargs)
-        self.prepare(**self.kwargs)
+        self.prepare(passphrase=passphrase, **self.kwargs)
 
     def prepare(self):
         """Pre-process configuration options"""
```

**Comment by ronf** [comment]
Thanks very much for the report! I'm not really sure how this got missed in my testing.

Looking more closely, I see some other problems with the 16becd8 as well. I think I may have taken the wrong approach there and may revert it completely and try something different. In any case, I'll try to provide a fix in the next day or so, and I'll probably end up pushing it out as a 2.8.1 release given the seriousness of this breakage. My apologies for that!

In the meantime, you don't actually need the changes in SSHConnectionOptions or in the Options class in misc.py. The following should be the only change needed to make connect() work again:

```patch
--- asyncssh-2.8.0/asyncssh/connection.py.orig	2021-11-05 17:47:19.000000000 -0700
+++ asyncssh-2.8.0/asyncssh/connection.py	2021-11-05 17:47:44.000000000 -0700
@@ -6887,7 +6887,7 @@
     options = SSHClientConnectionOptions(options, config=config, host=host,
                                          port=port, tunnel=tunnel,
                                          family=family, local_addr=local_addr,
-                                         **kwargs)
+                                         passphrase=passphrase, **kwargs)

     return await asyncio.wait_for(
         _connect(options, passphrase, loop, flags, conn_factory,
```

A complete fix would require a similar change in connect_reverse(), listen(), listen_reverse(), and get_server_host_key() to add back the passphrase argument when creating the options, but I think I can do something better when I commit the real fix.

**Comment by ronf** [comment]
Ok - I've reworked the bad commit here and the result is available as commit 4976307 in the "develop" branch. If you get a chance, could you give this a try? If it looks good, I'll push it to master and cut a new release to fix this.

**Comment by Ch3LL** [comment]
Thanks! I tested on the head of develop and its working now :)

**Comment by ronf** [comment]
Thanks for the confirmation! This is now released as version 2.8.1.
