### ISSUE TITLE
Python 3.10: Constructing a SSHConnectionOptions options failing

### ISSUE THREAD

**Issue by nagua** [ronf/asyncssh#483]
Hello everyone,

trying to construct a `SSHConnectionOptions` object like this:
```python
connect_options = asyncssh.connection.SSHConnectionOptions(user='a', password='b', known_hosts=None)
```

leads to this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home//.cache/pypoetry/virtualenvs/deploy-t7vdmGZu-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home//.cache/pypoetry/virtualenvs/deploy-t7vdmGZu-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home//.cache/pypoetry/virtualenvs/deploy-t7vdmGZu-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home//.cache/pypoetry/virtualenvs/deploy-t7vdmGZu-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home//repo/callisto/DSeries-Dynamark/deploy/src/deploy/cli.py", line 16, in cli
    asyncio.run(cli_async(deploy_targets, controller_tar, laserhead_tar, laserhead, controller))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home//repo/callisto/DSeries-Dynamark/deploy/src/deploy/cli.py", line 19, in cli_async
    await deploy_controller(controller_tar, controller)
  File "/home//repo/callisto/DSeries-Dynamark/deploy/src/deploy/cli.py", line 23, in deploy_controller
    connect_options = asyncssh.connection.SSHConnectionOptions(options=False, user='root', password='start123', known_hosts=None)
  File "/home//.cache/pypoetry/virtualenvs/deploy-t7vdmGZu-py3.10/lib/python3.10/site-packages/asyncssh/connection.py", line 6201, in __init__
    super().__init__(options=options, last_config=last_config, **kwargs)
  File "/home//.cache/pypoetry/virtualenvs/deploy-t7vdmGZu-py3.10/lib/python3.10/site-packages/asyncssh/misc.py", line 350, in __init__
    self.prepare(**self.kwargs)
TypeError: SSHConnectionOptions.prepare() got an unexpected keyword argument 'last_config'

```

I'm not sure if this really is a python3.10 error. But it seems to me like python didn't check if a named argument could be passed to a function or not and discarded it if it didn't. But now it errors on that. Also I don't see any test related to `SSHConnectionOptions` so I'm not sure if this is specific to my setup or if it was just overlooked somehow.

If I can help with anything about this error, please shout out. I'm happy to help!

Have a great day everyone.

**Comment by ronf** [comment]
You're using the wrong class here. The public API only documents SSHClientConnectionOptions and SSHServerConnectionOptions. Their parent class of SSHConnectionOptions is internal to the asyncssh.connection module and not meant to be accessed directly by applications.

In general, you should only use symbols available in the top-level "asyncssh" namespace and not its submodules. If you look at asyncssh/__init__.py, you can see what those are, or you can refer to the documentation at https://asyncssh.readthedocs.io/en/latest/api.html.

Let me know if you get this same error if you switch from asyncssh.connection.SSHConnectionOptions to asyncssh.SSHClientConnectionOptions.

**Comment by nagua** [comment]
Thanks again. This is working well!
