### ISSUE TITLE
Can't write bytes, can't write string when using  encoding=None

### ISSUE THREAD

**Issue by stuz5000** [ronf/asyncssh#526]
I've receiving none utf8 bytes from a remote shell because it sends non-utf8 data.
I tried setting encoding=None as recommended by this means I can no longer write to stdin at all:
                                                  
```
# An sshchannel
remoteStdin.write(stdinText)   # provide str
....
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/asyncssh/channel.py", line 932, in write
    self._send_buf.append((bytearray(encoded_data), datatype))
TypeError: string argument without an encoding
```
but 

```
remoteStdin.write(stdinText.encode("utf8"))   # Povide bytes
...
SSH session error: write() argument must be str, not bytes
```

To reproduce, I used[ this example](https://github.com/ronf/asyncssh/issues/521#issuecomment-1301544950), but provided  encoding=None to asyncssh.create_connection.

```
    class MySSHClientSession(asyncssh.SSHClientSession):
          ....

        def connection_made(self, chan: asyncssh.SSHClientChannel) -> None:
            self._remoteStdin = chan
            return super().connection_made(chan)

    conn, client = await asyncssh.create_connection(asyncssh.SSHClient,  # MySSHClient
                                                    encoding=None,
                                                    **ssh_kwargs)
    async with conn:
        chan, session = await conn.create_session(MySSHClientSession,
                                                  command=shellCommand,
                                                  term_type='xterm',
                                                  request_pty=pty,
                                                  # term_type='auto',
                                                  )
```

**Comment by ronf** [comment]
When using `encoding=None`, the `data` argument to the `write()` functions and returned data from the `read()` functions must always be of type `bytes`. Any conversion between strings and raw bytes is the responsibility of the caller in this case. When `encoding` is set to something other than `None`, the caller MUST only read and write string values, and these strings will automatically converted to/from raw bytes using `encode()` and `decode()` called with the requested encoding.

You can't mix things -- when you open the connection, you should decide whether you want to work with strings or bytes, and stay consistent with that. If you go with strings, make sure all data going both in & out is actually encoded in the requested encoding. As you noted, things will fail if you pick an encoding which doesn't match what the other system is sending (or expecting to receive).

In the case where you used `encoding=None` and passed in stdinText.encode("utf8"), I would have expected things to work. Did you get a traceback there? If so, could you provide that? I'm not seeing anything like the message "write() argument must be str, not bytes" in the AsyncSSH code. I'm wondering if maybe you are using a wrapper which is doing that enforcement without properly taking into account the need to pass in a `bytes` value when using `encoding=None`.

**Comment by stuz5000** [comment]
All of that is my understanding also.

> In the case where you used encoding=None and passed in stdinText.encode("utf8"), I would have expected things to work. Did you get a traceback there?

I did not. The write call is buffered. I guess there should be a coding/typing exception check before the buffer. Only an error is printed. There is a stack trace, but its for connection loss.

```
SSH session error: write() argument must be str, not bytes
Traceback (most recent call last):
  File "/home/user/sshTest.py", line 163, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user/sshTest.py", line 146, in main
    return await _run_client_interactive(
  File "/home/user/sshTest.py", line 137, in _run_client_interactive
    raise ConnectionError(f"Lost connection {repr(ssh_kwargs)}")
ConnectionError: Lost connection {'host': 'localhost'}
```

Here's the full example:

```
import asyncio
import io
import sys
from typing import Optional

import asyncssh

async def fileToAsyncReader(file=sys.stdin, loop=None):
    if loop is None:
        loop = asyncio.get_event_loop()
    stdinAsyncReader = asyncio.StreamReader()
    protocol = asyncio.StreamReaderProtocol(stdinAsyncReader)
    await loop.connect_read_pipe(lambda: protocol, file)
    return stdinAsyncReader

async def _run_client_interactive(
    shellCommand,
    stdinText, pty,
    printStderr, stderr,
    printStdout, stdout,
    ssh_kwargs,
    allowConnectionLost=False
):
    if stdinText and not stdinText.endswith('\n'): stdinText += '\n'

    async def stdinForwarder(remoteStdin: asyncssh.SSHClientChannel):
        try:
            # Pipe command in place of stdin:
            if stdinText is not None:
                remoteStdin.write(stdinText.encode("utf8"))
                # remoteStdin.write(stdinText)
                # remoteStdin.write("\nls xxx\n")
                # remoteStdin.write("\nexit\n")
                if not pty:
                    return
                # else keep open for stdin

            # with asPTY(file=sys.stdin, enabled=pty):
            # if 1:
            #     stdinAsyncReader = await fileToAsyncReader(file=sys.stdin)
            #     while True:
            #         res = await stdinAsyncReader.read(10)
            #         if not res: break
            #         print("WRITE STDING")
            #         remoteStdin.write(res.decode('utf8'))

        except Exception as e:
            print(e, file=sys.stderr)
            raise
            # debug.reportException()

        finally:
            if not remoteStdin.is_closing():
                if remoteStdin.can_write_eof():
                    remoteStdin.write_eof()

    class MySSHClientSession(asyncssh.SSHClientSession):
        lostConnection = False
        setNonBlockErr = False
        setNonBlockOut = False

        def eof_received(self):
            if self._remoteStdin is not None:
                self._remoteStdin.close()

        def exit_status_received(self, status):
            self.status = status

        def connection_made(self, chan: asyncssh.SSHClientChannel) -> None:
            self._remoteStdin = chan
            return super().connection_made(chan)

        def session_started(self) -> None:
            async def f():
                self._stdInWriterTask = asyncio.create_task(stdinForwarder(self._remoteStdin))

            asyncio.run_coroutine_threadsafe(f(), asyncio.get_event_loop())
            return super().session_started()

        def data_received(self, data: str, datatype: asyncssh.DataType) -> None:
            if datatype == asyncssh.EXTENDED_DATA_STDERR:
                if printStderr:
                    # if not self.setNonBlockErr:
                    #     fcntl.fcntl(sys.stderr.fileno(), fcntl.F_SETFL, os.O_NONBLOCK)
                    #     self.setNonBlockErr = True
                    sys.stderr.write(data)
                    sys.stderr.flush()
                stderr.write(data)
            else:
                if printStdout:
                    # if not self.setNonBlockOut:
                    #     fcntl.fcntl(sys.stdout.fileno(), fcntl.F_SETFL, os.O_NONBLOCK)
                    #     self.setNonBlockOut = True
                    sys.stdout.write(data)
                    sys.stdout.flush()
                stdout.write(data)

        def connection_lost(self, exc: Optional[Exception]) -> None:
            task = None
            try:
                task, self._stdInWriterTask = self._stdInWriterTask, None
            except AttributeError:
                pass

            if task is not None:
                task.cancel()

            if exc:
                sys.stderr.write(f'SSH session error: {str(exc)}\n')
                self.lostConnection = True
                # with unblockTTY():
                #     print('SSH session error: ' + str(exc), file=sys.stderr)

    # class MySSHClient(asyncssh.SSHClient):
    #     pass
    # def connection_made(self, conn: asyncssh.SSHClientConnection) -> None:
    #     print('Connection made to %s.' % conn.get_extra_info('peername')[0])
    #
    # def auth_completed(self) -> None:
    #     print('Authentication successful.')

    conn, client = await asyncssh.create_connection(asyncssh.SSHClient,  # MySSHClient
                                                    encoding=None,
                                                    **ssh_kwargs)
    async with conn:
        chan, session = await conn.create_session(MySSHClientSession,
                                                  command=shellCommand,
                                                  term_type='xterm',
                                                  request_pty=pty,
                                                  # term_type='auto',
                                                  )
        await chan.wait_closed()
        if session.lostConnection:
            if allowConnectionLost:
                return None
            else:
                raise ConnectionError(f"Lost connection {repr(ssh_kwargs)}")
        if session.status != 0:
            raise Exception(f"exit code={session.status}")



async def main():
    stdout = io.StringIO()
    stderr = io.StringIO()
    return await _run_client_interactive(
            shellCommand='bash',
            stdinText="""
            set -x
            set -e
            ls -l
            ls xxx
            ls -l 
            """,
            pty=False,
            printStderr=True, stderr=stderr,
            printStdout=True, stdout=stdout,
            ssh_kwargs=dict(host="localhost"),
            allowConnectionLost=False
    )


asyncio.run(main())
```

**Comment by stuz5000** [comment]
OK - I found I could print the exception:
```
        def connection_lost(self, exc: Optional[Exception]) -> None: 
             ...

                sys.stderr.write(f'SSH session error: {str(exc)}\n')
                traceback.print_exception(exc)
                self.lostConnection = True
                
```

which showed the problem is not with stdin, but silently sending bytes sys.stdout.write().

Using `sys.stdout.buffer.write()` fixed it.

Thanks.

**Comment by ronf** [comment]
Ah, yeah. Now that you mention it, I have run into this before, and have had to add ".buffer" when writing `bytes` to `sys.stdout` or `sys.stderr`. This actually shows up in some of my examples, such as https://asyncssh.readthedocs.io/en/latest/#direct-tcp-connections.
