### ISSUE TITLE
asyncssh causes mypy to crash

### ISSUE THREAD

**Issue by JCHacking** [ronf/asyncssh#542]
As soon as I install asyncssh and run mypy I get the following error:

Generated HTML report (via XSLT): C:\Users\jcmencia\PycharmProjects\test\reports\typing\index.html
Traceback (most recent call last):                                                                                                     
  File "<frozen runpy>", line 198, in _run_module_as_main                                                                              
  File "<frozen runpy>", line 88, in _run_code                                                                                         
  File "C:\Users\jcmencia\PycharmProjects\test\venv\Scripts\mypy.exe\__main__.py", line 7, in <module>            
  File "C:\Users\jcmencia\PycharmProjects\test\venv\Lib\site-packages\mypy\__main__.py", line 15, in console_entry
    main()                                                                                                                             
  File "mypy\main.py", line 95, in main                                                                                                
  File "mypy\main.py", line 174, in run_build                                                                                          
  File "mypy\build.py", line 194, in build                                                                                             
  File "mypy\build.py", line 277, in _build                                                                                            
  File "mypy\build.py", line 2923, in dispatch                                                                                         
  File "mypy\build.py", line 3320, in process_graph                                                                                    
  File "mypy\build.py", line 3443, in process_stale_scc                                                                                
  File "mypy\build.py", line 2504, in write_cache                                                                                      
  File "mypy\build.py", line 1574, in write_cache                                                                                      
  File "mypy\nodes.py", line 377, in serialize                                                                                         
  File "mypy\nodes.py", line 3841, in serialize
  File "mypy\nodes.py", line 3778, in serialize
  File "mypy\nodes.py", line 3514, in serialize
  File "mypy\types.py", line 2072, in serialize
  File "mypy\types.py", line 605, in serialize
  File "mypy\types.py", line 2876, in serialize
AssertionError: Internal error: unresolved placeholder type None

**Mypy Configuration**
mypy -> 1.0.0

[tool.mypy]
html_report = "reports/typing"
junit_xml = "reports/typing/junit.xml"
files = "src, tests"
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
disallow_untyped_calls = true
disallow_subclassing_any = true
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
warn_unreachable = true
strict_equality = true
strict_concatenate = true
plugins = ["pydantic.mypy"]
[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

**Edit**
- Without any configuration running `mypy src` also happens.
- Set up a new project from scratch with the same files and packages. Now it works... I'm still investigating what could cause the error.

**Comment by ronf** [comment]
It looks like you are running into https://github.com/python/mypy/issues/14631.  There's a fix available in mypy for this, but I'm not sure it has made it into a mypy release yet.

**Comment by ronf** [comment]
The code in AsyncSSH that triggers this internal error was causing other problems, so I added a workaround in commit 0d49161, which seems to avoid the error for me.

**Comment by JCHacking** [comment]
In the project in which it failed me, changing the dependency to the one of the commit that you indicate me, mypy no longer fails. So in my case it is also solved!

**Comment by ronf** [comment]
Great! Thanks for letting me know...

I'll try to put out a bug fix release of AsyncSSH with this change in the next few days.

**Comment by ronf** [comment]
This is now released in AsyncSSH 2.13.1.

**Comment by JCHacking** [comment]
Tested with the new version and it works, so the matter is finished. 👍

**Comment by ronf** [comment]
Thanks for the confirmation!
