### ISSUE TITLE
Fails to get response from command

### ISSUE THREAD

**Issue by xpertimage** [ronf/asyncssh#564]
Ron, I am trying to create an asyncssh script to fetch data from Cisco CUCM servers. The servers are running a linux OS. When you login to a device using ssh from a terminal there is a response of 'Command Line Interface is starting up, please wait ...\n\n\n\n' then some more data follows which I need to capture. In addition to the login data response I need to send a 'show status' command which will provide a response with more data that I need to capture. My problem is that when I use my python script to attaempt this the only data I get back is 'Command Line Interface is starting up, please wait ...\n\n\n\n'. 

I am sure the problem is that I just don't have a good understanding of how the 'conn.run() ' method works. Any help would be much appreciated.
 
I am using python 3.9.16  and below is my script:

```import asyncio
import asyncssh
import logging
import csv
import argparse
import time
import json
import sys
import textfsm

logging.basicConfig(filename='ssh_errors.log', level=logging.DEBUG)

password = sys.argv[1]
nodes = []
async def fetch_status(hostname, username, password):
    try:
        async with asyncssh.connect(
                hostname,
                username=username,
                password=password,
                known_hosts=None,
                encryption_algs="+aes256-cbc",
                kex_algs="+diffie-hellman-group1-sha1") as conn:
            output = await conn.run('show status')
            return output.stdout
    except asyncssh.Error as e:
        logging.error(f'Error connecting to {hostname}: {e}')
        return False

async def main():
    print('*************************************')
    print('Start of run')
    # List of routers to connect to 
    with open("CUCM_Inventory.json") as f:
        data = json.load(f)
    tasks = []
    for cluster in data['CUCMCluster']:
        if 'Top_Secret' in cluster:
            uname = cluster['Top_Secret']['Username']
            node = cluster['Top_Secret']['nodes']
            for ipadd in node:
                tasks.append(asyncio.create_task(fetch_status(ipadd, uname, password)))
            results = await asyncio.gather(*tasks)
            for result in results:
                print(result)

asyncio.run(main())
  ```

**Comment by ronf** [comment]
I'm not sure it makes a difference here, but one thing that jumped out at me is the use of create_task(). While it is legal to pass already-running tasks to gather(), you should be able to leave that out and just pass the fetch_status() coroutines directly to gather() and let it start the tasks.

As for fetch_status() itself, it looks reasonable to me as long as the devices support doing an "exec" over SSH (as opposed to requiring you to start a "shell" on them). Does it work with OpenSSH when you pass 'show status' as a command to run, without providing any other input, and does OpenSSH exit automatically after displaying all the output?

Do you see anything interesting in the debug log?

Also, while it's a bit of a long shot, is there any data returned in output.stderr?

**Comment by xpertimage** [comment]
Ron, thanks for the reply. I am attaching 2 ssh error logs. One is running the python script as I originally sent it to you. The second ssh error log is after removing the "asyncio.create_task". I get the same end result either way but maybe the error log can provide some helpful details.

Please let me know your thoughts.

Thanks!

[Without_Create_tasks_ssh_errors.log](https://github.com/ronf/asyncssh/files/11422300/Without_Create_tasks_ssh_errors.log)
[Create_tasks_ssh_errors.log](https://github.com/ronf/asyncssh/files/11422301/Create_tasks_ssh_errors.log)

**Comment by xpertimage** [comment]
Ron, regarding your reply about "Does it work with OpenSSH when you pass 'show status' as a command to run, without providing any other input, and does OpenSSH exit automatically after displaying all the output?" 

So if I SSH to one of these devices using a terminal, I can login and after the banner displays I can enter "show status" and I get the expected results however if I enter "run show status" it fails.  Also I checked stderr and the output is below:

``` *************************************
Start of run
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:503)
        at java.lang.Integer.parseInt(Integer.java:526)
        at sdMain.initialize(sdMain.java:501)
        at sdMain.main(sdMain.java:676)
stty: standard input: Inappropriate ioctl for device

stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:503)
        at java.lang.Integer.parseInt(Integer.java:526)
        at sdMain.initialize(sdMain.java:501)
        at sdMain.main(sdMain.java:676)
stty: standard input: Inappropriate ioctl for device

stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:503)
        at java.lang.Integer.parseInt(Integer.java:526)
        at sdMain.initialize(sdMain.java:501)
        at sdMain.main(sdMain.java:676)
stty: standard input: Inappropriate ioctl for device

(IPT) [kctl@gmlcpansvlp0003 python-voice-infra-healthcheck]$  ```

**Comment by ronf** [comment]
Sorry, when I asked about passing 'show status' as a command to run, I mean something like:

```
ssh <target_machine> show status
```

Specifically, I was looking to see if you could do that without providing any input from the terminal, and whether it generated the output you wanted and exited ssh automatically when that was done.

I'm not surprised removing create_task() didn't have an affect, but I thought I'd mention it just as a way to simplify the code a bit in the future.

As for the logs, it looks like you are successfully sending authenticating and sending the "show status" command via SSH to the target, but the target is failing immediately with an exit status of 1, without generating any output. The logs are interleaved across 3 sessions, but if I pull out just one of those, it looks something like:

```
INFO:asyncssh:[conn=0, chan=0] Requesting new SSH session
INFO:asyncssh:[conn=0, chan=0]   Command: show status
INFO:asyncssh:[conn=0, chan=0] Received exit status 1
INFO:asyncssh:[conn=0, chan=0] Received channel close
INFO:asyncssh:[conn=0, chan=0] Channel closed
INFO:asyncssh:[conn=0] Closing connection
INFO:asyncssh:[conn=0] Sending disconnect: Disconnected by application (11)
INFO:asyncssh:[conn=0] Connection closed
```

So, I think the problem is that the target device doesn't properly handle "exec" requests. If I'm right about this, passing a command to OpenSSH like I listed above should also fail in a similar manner.

Instead of passing in a command, you could try passing in something like `input='show status\n'` and see if that helps. That's basically telling AsyncSSH to send 'show status' followed by a newline on stdin after a "shell" session is established, and then collect up all the output as you did before. I've heard about cases where this doesn't work, though, if the device is not ready to accept input right away. In that case, you may need to use `create_process()` instead of `run()` and add some code which waits for particular output (like a prompt) before sending a command, or possibly just add a delay with `asyncio.sleep()` before you write your input. You could then either read the output in a loop or call `wait()` on the process to get back the same result you would have gotten from `run()`.

I'm not sure how to make sense out of the stderr output you showed there. Are you expecting a Java program to be running on any of the systems involved here? Also, you are getting the error 3 times, which matches opening 3 sessions, but any given session's output should only see output from that one session. When you checked stderr, were you looking at stderr on the client system, or looking at the contents of `output.stderr`?

**Comment by xpertimage** [comment]
Ron, after a full day I feel I made a little progress. This is all in an effort to login to a device, send a "show status" command and capture the output from both the login and the show status.  So I somehow found myself creating a process and using the 'communicate' method. It seems like the communicate method should really simplify my code if I understand it. I have attached the latest version of my python code, SSH error log and screen output. For some reason I am getting errors on stderr when getting the login response (even though I get some of the response) however trying to send the command is not working at all. Please let me know what I am missing.

```import asyncio, asyncssh, sys
import logging
import time


PROMPT = "admin:"

logging.basicConfig(filename='ssh_errors.log', level=logging.DEBUG)

class Target:

    async def _run_client(self, cmdsequence, ip, **kwargs):
        print(ip)
        print()
        async with asyncssh.connect(ip, **kwargs) as conn:
            process1 = await conn.create_process()
            try:
                stdout, stderr = await process1.communicate(None)
                print('Process1')
                print('stdout:', stdout)
                print('stderr:', stderr)
            except BaseException as e:
                print("Error Process1: ", e)
            process2 = await conn.create_process()
            for cmd in cmdsequence:
                try:
                    stdout, stderr  = await process2.communicate(cmd)
                    print('Process2')
                    print('stdout:', stdout)
                    print('stderr:', stderr)
                except BaseException as e:
                    print("Error Process2: ", e)

    def remote_cmd(self, cmdsequence, ip, **kwargs):
        try:
            asyncio.get_event_loop().run_until_complete(
                self._run_client(cmdsequence, ip, **kwargs))
        except (OSError, asyncssh.Error) as exc:
            print('SSH connection failed: ' + str(exc))


tg = Target()
tg.remote_cmd(['show status'], '146.34.1.28', username='HOU150NXAFC0', password= sys.argv[1])  ``` 



``` DEBUG:asyncio:Using selector: EpollSelector
INFO:asyncssh:Opening SSH connection to 146.34.1.28, port 22
INFO:asyncssh:[conn=0] Connected to SSH server at 146.34.1.28, port 22
INFO:asyncssh:[conn=0]   Local address: 139.65.138.35, port 44950
INFO:asyncssh:[conn=0]   Peer address: 146.34.1.28, port 22
DEBUG:asyncssh:[conn=0] Sending version SSH-2.0-AsyncSSH_2.13.1
DEBUG:asyncssh:[conn=0] Received version SSH-2.0-OpenSSH_7.5 PKIX[10.1]
DEBUG:asyncssh:[conn=0] Requesting key exchange
DEBUG:asyncssh:[conn=0] Received key exchange request
DEBUG:asyncssh:[conn=0] Beginning key exchange
DEBUG:asyncssh:[conn=0] Completed key exchange
INFO:asyncssh:[conn=0] Beginning auth for user HOU150NXAFC0
DEBUG:asyncssh:[conn=0] Trying public key auth with rsa-sha2-256 key
DEBUG:asyncssh:[conn=0] Trying password auth
INFO:asyncssh:[conn=0] Auth for user HOU150NXAFC0 succeeded
DEBUG:asyncssh:[conn=0, chan=0] Set write buffer limits: low-water=16384, high-water=65536
INFO:asyncssh:[conn=0, chan=0] Requesting new SSH session
DEBUG:asyncssh:[conn=0] Received unknown global request: hostkeys-00@openssh.com
INFO:asyncssh:[conn=0, chan=0]   Interactive shell requested
INFO:asyncssh:[conn=0, chan=0] Received exit status 1
INFO:asyncssh:[conn=0, chan=0] Received channel close
INFO:asyncssh:[conn=0, chan=0] Channel closed
DEBUG:asyncssh:[conn=0, chan=1] Set write buffer limits: low-water=16384, high-water=65536
INFO:asyncssh:[conn=0, chan=1] Requesting new SSH session
INFO:asyncssh:[conn=0, chan=1]   Interactive shell requested
INFO:asyncssh:[conn=0, chan=1] Received exit status 1
INFO:asyncssh:[conn=0, chan=1] Received channel close
INFO:asyncssh:[conn=0, chan=1] Channel closed
INFO:asyncssh:[conn=0] Closing connection
INFO:asyncssh:[conn=0] Sending disconnect: Disconnected by application (11)
INFO:asyncssh:[conn=0] Connection closed
 ```



``` Process1
stdout: Command Line Interface is starting up, please wait ...




stderr: stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:503)
        at java.lang.Integer.parseInt(Integer.java:526)
        at sdMain.initialize(sdMain.java:501)
        at sdMain.main(sdMain.java:676)
stty: standard input: Inappropriate ioctl for device

Process2
stdout: Command Line Interface is starting up, please wait ...




stderr: stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:503)
        at java.lang.Integer.parseInt(Integer.java:526)
        at sdMain.initialize(sdMain.java:501)
        at sdMain.main(sdMain.java:676)
stty: standard input: Inappropriate ioctl for device
 ```

**Comment by ronf** [comment]
The communicate() method is intended to let you provide input to stdin on a session and wait for output back on stdout/stderr. However, it closes stdin on the session as soon as the optional `input` is provided, and will wait indefinitely for all the output on stdout and stderr, unless you provide a timeout. It really isn't designed to alternate between reading output and providing additional input. For that, you'd need to use `write()` on stdin and `read()` or a variant of it such as `readexactly()`, `readline()`, or `readuntil()` on stdout/stderr until you get the output you're waiting for.

Since you are seeing the part about the CLI multiple times, it looks like it is going to start a new CLI shell for every new session/process you create, so I think you'll need to find a way to do this with only a single instance of process, and that means avoiding any calls which write EOF or read until EOF.

As for the errors you're seeing on stderr, it looks to me like maybe the remote system only functions correctly when a pseudo-tty is created. You can do that by passing in `term_type` when you open the session. This will probably get rid of the stty errors, and in the process maybe also the Java error. If it does, that may help you get the shell started up successfully so you can write the command and read the response. In fact, you may want to do that with the version using `run()`, and you may find it just works. You can try both with a command specified and with `input='show status\n'` if that doesn't work.

**Comment by ronf** [comment]
Closing due to inactivity. Feel free to reopen this or open a new issue if you need anything else.
