### ISSUE TITLE
Failes to parse `Match tagged [pattern]` in ssh_config

### ISSUE THREAD

**Issue by linsein** [ronf/asyncssh#624]
`Tag` is a new feature of [openssh 9.4](https://www.openssh.com/txt/release-9.4) released on 2023-08-10
# Environments
+ Python: 3.11.6
+ asyncssh: 2.14.2
+ OS: Arch Linux  6.6.11-2-lts

# Files
## `main.py`
```python
import asyncio
import asyncssh


async def main():
    async with asyncssh.connect("dev", config="./config") as conn:
        await conn.run("whoami")

if __name__ == '__main__':
    asyncio.run(main())
```
## `config`
```
Host dev
	Hostname localhost
	Port 2022
	Tag allow_untrusted

Match tagged allow_untrusted
   	UserKnownHostsFile /dev/null
 	StrictHostKeyChecking no
```

# Outputs
```
> python main.py                                                                                                                              ~/source/exp/foo
Traceback (most recent call last):
  File "/home/lindsay/source/exp/foo/main.py", line 11, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/lindsay/source/exp/foo/main.py", line 6, in main
    async with asyncssh.connect("dev", known_hosts=None, config="./config") as conn:
  File "/usr/lib/python3.11/site-packages/asyncssh/misc.py", line 274, in __aenter__
    self._coro_result = await self._coro
                        ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asyncssh/connection.py", line 8264, in connect
    new_options = cast(SSHClientConnectionOptions, await _run_in_executor(
                                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asyncssh/connection.py", line 511, in _run_in_executor
    return await loop.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asyncssh/connection.py", line 6638, in __init__
    super().__init__(options=options, last_config=last_config, **kwargs)
  File "/usr/lib/python3.11/site-packages/asyncssh/misc.py", line 350, in __init__
    self.prepare(**self.kwargs)
  File "/usr/lib/python3.11/site-packages/asyncssh/connection.py", line 7339, in prepare
    config = SSHClientConfig.load(last_config, config, reload,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asyncssh/config.py", line 394, in load
    config.parse(Path(path))
  File "/usr/lib/python3.11/site-packages/asyncssh/config.py", line 354, in parse
    handler(self, option, args)
  File "/usr/lib/python3.11/site-packages/asyncssh/config.py", line 167, in _match
    self._error('Invalid match condition')
  File "/usr/lib/python3.11/site-packages/asyncssh/config.py", line 81, in _error
    raise ConfigParseError('%s line %s: %s' % (self._path, self._line_no,
asyncssh.config.ConfigParseError: config line 5: Invalid match condition
```

**Comment by ronf** [comment]
As you said, the "Tag" and "Match Tagged" options appears to be a new feature added to OpenSSH only in version 9.4 (released about 4 months ago). I can look into adding it, but it is not currently supported in AsyncSSH, triggering the parse error.

**Comment by ronf** [comment]
I wasn't able to find much detail about OpenSSH's tag implementation, beyond a brief reference in the ssh_config man page and the OpenSSH changelog.

Do you know if multiple tags can be set at once when parsing the config file, such that matching on any of them would be considered a match, or does setting a tag overwrite the previous tag that was set similar to pf.conf, such that only the most recent tag which was set will match in 'Match tagged'?

Do you know if patterns are allowed in 'Match tagged'? What about negation? Also, are multiple comma-separated patterns allowed like in 'Match host', where all of the patterns must match?

**Comment by ronf** [comment]
To answer my own questions, here's what it looks like from the code:

- Only a single tag value can be set at any given time - setting a new tag overwrites the previous one.
- When matching, pattern lists and negation are supported.  It looks like it behaves like matching user or local user rather than hostname, with the difference being the match is case-sensitive, while hostname matches are not.

Is this consistent with what you've seen?

**Comment by ronf** [comment]
I think this is all that is needed to make this work:

```patch
diff --git a/asyncssh/config.py b/asyncssh/config.py
index d481cc2..351648d 100644
--- a/asyncssh/config.py
+++ b/asyncssh/config.py
@@ -447,6 +447,8 @@ class SSHClientConfig(SSHConfig):
             return self._local_user
         elif match == 'user':
             return self._options.get('User', self._local_user)
+        elif match == 'tagged':
+            return self._options.get('Tag', '')
         else:
             return None

@@ -561,6 +563,7 @@ class SSHClientConfig(SSHConfig):
         ('ServerAliveCountMax',             SSHConfig._set_int),
         ('ServerAliveInterval',             SSHConfig._set_int),
         ('SetEnv',                          SSHConfig._append_string_list),
+        ('Tag',                             SSHConfig._set_string),
         ('TCPKeepAlive',                    SSHConfig._set_bool),
         ('User',                            SSHConfig._set_string),
         ('UserKnownHostsFile',              SSHConfig._set_string_list)
```

**Comment by ronf** [comment]
Thanks for confirming!

I'll check this in soon to the "develop" branch and make sure it gets into the next release.

**Comment by ronf** [comment]
This is now in the "develop" branch as commit 88e87eb.
