### ISSUE TITLE
sftp.put returning asyncssh.sftp.SFTPFailure: Failure

### ISSUE THREAD

**Issue by bronzinni** [ronf/asyncssh#653]
Hi,

I am attempting something relatively simple. I have a path stored in variable `src_file` and I want to transfer it. I attempt to do the following:

```
        # establish SFTP connection
        async with asyncssh.connect(conf['sftphost'], username=conf['sftpuser'], password=conf['sftppass']) as conn:
            async with conn.start_sftp_client() as sftp:
                try:
                    await sftp.put(src_file, remotepath=conf['remote_path'])
                except Exception as e:
                    logging.info(f'{e}')
```

The Exception I catch is just "Failure".
If I avoid trying to handle the Exception as above I get:

```
2024-04-24 10:51:38 - Task exception was never retrieved
future: <Task finished name='Task-3' coro=<worker() done, defined at /home/e340115/gitrepos/igs_redirector/igs_redirector.py:51> exception=NameError("name 'SFTPError' is not defined")>
Traceback (most recent call last):
  File "/home/e340115/gitrepos/igs_redirector/igs_redirector.py", line 60, in worker
    await sftp.put(src_file, remotepath=conf['remote_path'])
  File "/home/e340115/.local/lib/python3.10/site-packages/asyncssh/sftp.py", line 3907, in put
    await self._begin_copy(local_fs, self, localpaths, remotepath, 'put',
  File "/home/e340115/.local/lib/python3.10/site-packages/asyncssh/sftp.py", line 3698, in _begin_copy
    await self._copy(srcfs, dstfs, srcfile, dstfile, srcname.attrs,
  File "/home/e340115/.local/lib/python3.10/site-packages/asyncssh/sftp.py", line 3617, in _copy
    await _SFTPFileCopier(block_size, max_requests, 0,
  File "/home/e340115/.local/lib/python3.10/site-packages/asyncssh/sftp.py", line 780, in run
    self._dst = await self._dstfs.open(self._dstpath, 'wb')
  File "/home/e340115/.local/lib/python3.10/site-packages/asyncssh/sftp.py", line 4449, in open
    handle = await self._handler.open(path, pflags, attrs)
  File "/home/e340115/.local/lib/python3.10/site-packages/asyncssh/sftp.py", line 2637, in open
    return cast(bytes, await self._make_request(
  File "/home/e340115/.local/lib/python3.10/site-packages/asyncssh/sftp.py", line 2454, in _make_request
    result = self._packet_handlers[resptype](self, resp)
  File "/home/e340115/.local/lib/python3.10/site-packages/asyncssh/sftp.py", line 2470, in _process_status
    raise exc
asyncssh.sftp.SFTPFailure: Failure
```

This happens on Ubuntu 22.04.4 with asyncssh 2.14.2 installed via pip.

**Comment by bronzinni** [comment]
Hi, thanks for your fast reply.

In the meantime I have made it work with an external bash script, so all write permissions etc. should be in order.
I am using absolute paths and there is no missing subdirectories.

I did not make any reference to SFTPError. But I can use for example:

```
except asyncssh.SFTPError as e:
    logging.info(f'Error caught: {e}')
```

And I then get:

```
2024-04-25 15:57:33 - Opening SSH connection to localhost, port 22
2024-04-25 15:57:33 - [conn=23] Connected to SSH server at localhost, port 22
2024-04-25 15:57:33 - [conn=23]   Local address: 127.0.0.1, port 34986
2024-04-25 15:57:33 - [conn=23]   Peer address: 127.0.0.1, port 22
2024-04-25 15:57:33 - [conn=23] Beginning auth for user username_redacted
2024-04-25 15:57:33 - [conn=23] Auth for user username_redacted succeeded
2024-04-25 15:57:33 - [conn=23, chan=0] Requesting new SSH session
2024-04-25 15:57:33 - [conn=23, chan=0]   Subsystem: sftp
2024-04-25 15:57:33 - [conn=23, chan=0] Starting SFTP client
2024-04-25 15:57:33 - [conn=23, chan=0] Starting SFTP put of /full/path/to/file to /path/to/dir/
2024-04-25 15:57:33 - [conn=23, chan=0]   Copying file /full/path/to/file to /path/to/dir/
2024-04-25 15:57:33 - Error caught: Failure
2024-04-25 15:57:33 - [conn=23, chan=0] Received exit status 0
2024-04-25 15:57:33 - [conn=23, chan=0] Received channel close
2024-04-25 15:57:33 - [conn=23, chan=0] SFTP client exited
2024-04-25 15:57:33 - [conn=23, chan=0] Closing channel
2024-04-25 15:57:33 - [conn=23, chan=0] Channel closed
2024-04-25 15:57:33 - [conn=23] Closing connection
2024-04-25 15:57:33 - [conn=23] Sending disconnect: Disconnected by application (11)
2024-04-25 15:57:33 - [conn=23] Connection closed
```

**Comment by ronf** [comment]
Can you try increasing the log level to DEBUG and set the AsyncSSH debug level to 2? This should provide more information about the specific SFTP request which is triggering the failure. The calls for this are:

```python
    asyncssh.set_log_level('DEBUG')
    asyncssh.set_debug_level(2)
```

In your log here, I see you're connecting to localhost, but is that just for this example?

**Comment by bronzinni** [comment]
In this test I am using my local ssh server. Once it works, I will change it.

Changing the log settings I get a bit more information around the point of failure:

```

2024-04-26 10:35:50 - [conn=0] Auth for user username_redacted succeeded
2024-04-26 10:35:50 - [conn=0, chan=0] Set write buffer limits: low-water=16384, high-water=65536
2024-04-26 10:35:50 - [conn=0, chan=0] Requesting new SSH session
2024-04-26 10:35:50 - [conn=0, chan=0]   Initial recv window 2097152, packet size 32768
2024-04-26 10:35:50 - [conn=0] Received unknown global request: hostkeys-00@openssh.com
2024-04-26 10:35:50 - [conn=0, chan=0]   Initial send window 0, packet size 32768
2024-04-26 10:35:50 - [conn=0, chan=0]   Subsystem: sftp
2024-04-26 10:35:50 - [conn=0, chan=0] Received window adjust of 2097152 bytes, new window 2097152
2024-04-26 10:35:50 - [conn=0, chan=0] Starting SFTP client
2024-04-26 10:35:50 - [conn=0, chan=0] Sending init, version=3
2024-04-26 10:35:50 - [conn=0, chan=0] Sending 9 data bytes
2024-04-26 10:35:50 - [conn=0, chan=0] Reading from channel started
2024-04-26 10:35:50 - [conn=0, chan=0] Received 242 data bytes
2024-04-26 10:35:50 - [conn=0, chan=0] Received version=3, extensions:
2024-04-26 10:35:50 - [conn=0, chan=0]   posix-rename@openssh.com: 1
2024-04-26 10:35:50 - [conn=0, chan=0]   statvfs@openssh.com: 2
2024-04-26 10:35:50 - [conn=0, chan=0]   fstatvfs@openssh.com: 2
2024-04-26 10:35:50 - [conn=0, chan=0]   hardlink@openssh.com: 1
2024-04-26 10:35:50 - [conn=0, chan=0]   fsync@openssh.com: 1
2024-04-26 10:35:50 - [conn=0, chan=0]   lsetstat@openssh.com: 1
2024-04-26 10:35:50 - [conn=0, chan=0]   limits@openssh.com: 1
2024-04-26 10:35:50 - [conn=0, chan=0]   expand-path@openssh.com: 1
2024-04-26 10:35:50 - [conn=0, chan=0] Adjusting for non-standard symlink implementation
2024-04-26 10:35:50 - [conn=0, chan=0] Starting SFTP put of /full/path/to/file to /path/to/dir/
2024-04-26 10:35:50 - [conn=0, chan=0] Sending stat for /path/to/dir/
2024-04-26 10:35:50 - [conn=0, chan=0] Sending 40 data bytes
2024-04-26 10:35:50 - [conn=0, chan=0] Received 33 data bytes
2024-04-26 10:35:50 - [conn=0, chan=0]   Copying file /full/path/to/file to /path/to/dir/
2024-04-26 10:35:50 - [conn=0, chan=0] Sending open for /path/to/dir/, mode 0x1a
2024-04-26 10:35:50 - [conn=0, chan=0] Sending 48 data bytes
2024-04-26 10:35:50 - [conn=0, chan=0] Received 28 data bytes
2024-04-26 10:35:50 - Error caught: Failure
2024-04-26 10:35:50 - [conn=0, chan=0] Sending EOF
2024-04-26 10:35:50 - [conn=0, chan=0] Received EOF
2024-04-26 10:35:50 - [conn=0, chan=0] Received exit status 0
2024-04-26 10:35:50 - [conn=0, chan=0] Received channel close
2024-04-26 10:35:50 - [conn=0, chan=0] SFTP client exited
```


Thanks again for helping me out.

**Comment by ronf** [comment]
Ok - this confirms that the error is happening right on the initial "open" call. From the output, it looks like the server is OpenSSH, and you are using SFTP version 3 (the max OpenSSH supports).

Are you really seeing the same destination pathname in the "open" message that you are seeing in the "put" message? If that destination is a directory, it should be adding the filename from the source path before attempting to call open. Not doing so and attempt to call "open" on the directory would explain this failure.

You wouldn't happen to be trying to put to path which is a symlink, would you? I haven't tested that, but it seems like this might confuse the "stat" call it is making to determine if the target is a directory.

If you replace the "/path/to/dir/" with a path to the target filename in that dir you want to copy into, does that work around the problem? Also, if you remove the trailing slash from the "/path/to/dir/" (if there is one), does that make a difference?

**Comment by bronzinni** [comment]
> Are you really seeing the same destination pathname in the "open" message that you are seeing in the "put" message? If that destination is a directory, it should be adding the filename from the source path before attempting to call open. Not doing so and attempt to call "open" on the directory would explain this failure.

I assume these are the lines you are asking about?

```
2024-04-26 10:35:50 - [conn=0, chan=0]   Copying file /full/path/to/file to /path/to/dir/
2024-04-26 10:35:50 - [conn=0, chan=0] Sending open for /path/to/dir/, mode 0x1a
```

The destination path `/path/to/dir` does not include the file and is the same in both places.

> You wouldn't happen to be trying to put to path which is a symlink, would you? I haven't tested that, but it seems like this might confuse the "stat" call it is making to determine if the target is a directory.

The parent directory is a mounted network drive, but there shouldn't be any symlinks.

> If you replace the "/path/to/dir/" with a path to the target filename in that dir you want to copy into, does that work around the problem? Also, if you remove the trailing slash from the "/path/to/dir/" (if there is one), does that make a difference?

With a target filename I get `Error caught: No such file`.
Without trailing slash I get `Error caught: Permission denied`.

**Comment by ronf** [comment]
So far, I'm unable to reproduce this issue here, with the destination either being a directory or a mount point. A key difference in the working case is that the filename is added to both the "Copying file" and the "Sending open" message when the destination is not already a file. In other words, I'd expect the messages to be something like:

```
INFO:asyncssh.sftp:[conn=0, chan=0] Starting SFTP put of /full/path/to/file to /path/to/dir/
DEBUG:asyncssh.sftp:[conn=0, chan=0] Sending stat for /path/to/dir/
DEBUG:asyncssh.sftp:[conn=0, chan=0] Received type: directory, size: 384, uid: 0, gid: 0, permissions: 41777, atime: Mon Apr 29 07:27:55 2024, mtime: Mon Apr 29 17:15:57 2024
INFO:asyncssh.sftp:[conn=0, chan=0]   Copying file /full/path/to/file to /path/to/dir/file
DEBUG:asyncssh.sftp:[conn=0, chan=0] Sending open for /path/to/dir/file, mode 0x1a
DEBUG:asyncssh.sftp:[conn=0, chan=0] Received handle 00000000
DEBUG:asyncssh.sftp:[conn=0, chan=0] Sending close for handle 00000000
DEBUG:asyncssh.sftp:[conn=0, chan=0] Received OK
```

Could you increase your log level to DEBUG and see what you get from the "stat" call on the remote path?

**Comment by bronzinni** [comment]
I managed to get it to work now after writing a different solution based on async call of a bash script.
I did have debug logging set, but I never got the "Received type" message and only got a failure after trying to copy, so I had expected the dir to be alright.
Embarrassingly, it boils down passing the wrong directory. Sorry for taking your time.

**Comment by ronf** [comment]
No problem - glad you figured it out.

The destination not existing would explain why AsyncSSH wasn't treating it as a directory. It was trying to write into a file with the target name, without appending the source filename. If something in that path didn't exist, you'd get the "No such file" error when you added the filename explicitly, and without that it might be trying to write to something in the parent directory, which could explain the "Permission denied" error if you didn't have write access there.

Regarding the debug logging, did you reset the log level in the "logging" module? It's not good enough to set the AsyncSSH debug level. You also need to do something like:

```python
    logging.basicConfig(level='DEBUG')
```

Otherwise, by default, I think you only get INFO and higher.

**Comment by bronzinni** [comment]
I did not realise that I should see a 'Received type' message before spotting it in your post above.
Indeed, the user would not have permission to write to the parent directory, which made the transfer fail.
I did also change the `logging.basicConfig` as you suggest.

Closing now. Thanks again for you help.
