### ISSUE TITLE
IncompleteReadError after login to Cisco Catalyst blade switches

### ISSUE THREAD

**Issue by throwaway2324** [ronf/asyncssh#97]
```
import asyncssh, asyncio

async def main():
  async with asyncssh.connect(host, username=username, password=password) as conn:
    stdin, stdout, stderr = await conn.open_session()
    result = await stdout.readuntil(">")
    print("A:"+repr(result))
    stdin.write("enable\r")
    result = await stdout.readline()
    print("B:"+repr(result))
    stdin.write(enable_password+"\r")
    result = await stdout.readuntil("#")
    print("C:"+repr(result))
    stdin.write("terminal pager 0\r")
    result = await stdout.readuntil("#")
    print("D:"+repr(result))
    stdin.write("terminal length 0\r")
    result = await stdout.readuntil("#")
    print("E:"+repr(result))
    stdin.write("sh run\r")
    result = await stdout.readuntil("end\r\n")
    print("F:"+repr(result))

loop = asyncio.get_event_loop()
results = loop.run_until_complete(main())
```

On other switch models, this fetches the switch configuration. On my Catalyst blade switch running IOS 12.2, I get an IncompleteReadError:

```
A:BANNER\r\n\r\nprompt>'
B:'enable\r\n'
Traceback (most recent call last):
  File "/local0/grabber_env/testcase.py", line 31, in <module>
    results = loop.run_until_complete(main())
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/local0/grabber_env/testcase.py", line 18, in main
    result = await stdout.readuntil("#")
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/coroutines.py", line 208, in coro
    res = yield from res
  File "/local0/grabber_env/lib/python3.5/site-packages/asyncssh/stream.py", line 479, in readuntil
    raise asyncio.IncompleteReadError(buf, None)
asyncio.streams.IncompleteReadError: 10 bytes read on a total of None expected bytes
```

Any ideas? This works fine with the ssh command line client.

**Comment by ronf** [comment]
The error here suggests that some other exception was returned while you were trying to read, suggesting that the connection probably closed in some unclean way. If you catch the IncompleteReadError, you can try reading again to find out what the exception is associated with the connection failure.

Wouldn't the "enable" command normally request a password from you? Could it be you're getting that prompt instead of getting the '#' you are expecting and then the switch is eventually timing out?

According to the error, you are also getting 10 bytes of data before the exception. You might try printing that out to see what it is. It would be stored in the "partial" field of the IncompleteReadError exception if you put in a try/except for that.

**Comment by throwaway2324** [comment]
Thanks. partial contains "Password: " as I'd expect. I changed the code to:
```
    stdin, stdout, stderr = await conn.open_session(term_type="ansi")
    result = await stdout.readuntil(">")
    print("A:"+repr(result))
    stdin.write("enable\r")
    result = await stdout.readuntil("Password: ")
    print("B:"+repr(result))
    stdin.write(enable_password+"\r")
    result = await stdout.readuntil("#")
    print("C:"+repr(result))
    stdin.write("terminal pager 0\r")
    result = await stdout.readuntil("#")
    print("D:"+repr(result))
    stdin.write("terminal length 0\r")
    result = await stdout.readuntil("#")
    print("E:"+repr(result))
    stdin.write("sh run\r")
    result = await stdout.readuntil("end\r\n")
    print("F:"+repr(result))
```
but I get disconnected straight away (on the blade switch, code still fetches the config in the other switches):
```
Traceback (most recent call last):
  File "/local0/grabber_env/testcase.py", line 31, in <module>
    results = loop.run_until_complete(main())
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/local0/grabber_env/testcase.py", line 18, in main
    result = await stdout.readuntil("#")
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/asyncio/coroutines.py", line 208, in coro
    res = yield from res
  File "/local0/grabber_env/lib/python3.5/site-packages/asyncssh/stream.py", line 481, in readuntil
    raise recv_buf.pop(0)
  File "/local0/grabber_env/lib/python3.5/site-packages/asyncssh/connection.py", line 477, in data_received
    while self._inpbuf and self._recv_handler():
  File "/local0/grabber_env/lib/python3.5/site-packages/asyncssh/connection.py", line 712, in _recv_packet
    raise DisconnectError(DISC_PROTOCOL_ERROR, str(exc)) from None
asyncssh.misc.DisconnectError: Disconnect Error: Incomplete packet
```

The enable password is correct (it works if I type it in a ssh command line session) so I'm not sure why I'm getting disconnected.

**Comment by ronf** [comment]
That is really odd - the "Incomplete packet" error is pretty odd. It suggests either a protocol error in the SSH implementation on the switch, or it dropping the connection in the _middle_ of sending an SSH packet. Of course, it could also be a bug in AsyncSSH, but I haven't seen reports of anything like that from anyone else.

You might want to try adding some debugging code in connection.py of a try/except around the "self.process_packet()" call which catches the DisconnectError. When you get the exception, print out pkttype and payload.

**Comment by throwaway2324** [comment]
I changed the handler around
https://github.com/ronf/asyncssh/blob/master/asyncssh/connection.py#L711 to read:

```
        except PacketDecodeError as exc:
            print("exc:"+repr(exc))
            print("pkttype:"+repr(pkttype))
            print("payload:"+repr(payload))
            raise DisconnectError(DISC_PROTOCOL_ERROR, str(exc)) from None
```
and got:
```
exc:PacketDecodeError('Incomplete packet',)
pkttype:2
payload:b'\x02\x00\x00\x00\x18'
```

**Comment by ronf** [comment]
Thanks. Packet type 2 is MSG_IGNORE, which takes a single "String" argument. The 4 bytes after the \x02 there would be the length of the string (24 bytes in this case), but then there should be an additional 24 bytes of payload data and that seems to be missing. So, it really would suggest that the blade switches are sending an invalid SSH packet. I don't know why only AsyncSSH would trigger this, though.

Is there any logging you can enable on the switch side to try and help diagnose this?

**Comment by throwaway2324** [comment]
I'll see what I can do. Thanks for looking into this.

**Comment by throwaway2324** [comment]
Got some logs!

```
6y15w: SSH0: starting SSH control process
6y15w: SSH0: sent protocol version id SSH-2.0-Cisco-1.25
6y15w: SSH0: protocol version id is - SSH-2.0-AsyncSSH_1.10.1
6y15w: SSH2 0: send: len 280 (includes padlen 4)
6y15w: SSH2 0: SSH2_MSG_KEXINIT sent
6y15w: SSH2 0: ssh_receive: 1460 bytes received
6y15w: SSH2 0: input: packet len 1960
6y15w: SSH2 0: partial packet 8, need 1952, maclen 0
6y15w: SSH2 0: ssh_receive: 500 bytes received
6y15w: SSH2 0: partial packet 8, need 1952, maclen 0
6y15w: SSH2 0: input: padlen 7
6y15w: SSH2 0: received packet type 20
6y15w: SSH2 0: SSH2_MSG_KEXINIT received
6y15w: SSH2: kex: client->server aes256-cbc hmac-sha1 none
6y15w: SSH2: kex: server->client aes256-cbc hmac-sha1 none
6y15w: SSH2 0: expecting SSH2_MSG_KEXDH_INIT
6y15w: SSH2 0: ssh_receive: 144 bytes received
6y15w: SSH2 0: input: packet len 144
6y15w: SSH2 0: partial packet 8, need 136, maclen 0
6y15w: SSH2 0: input: padlen 6
6y15w: SSH2 0: received packet type 30
6y15w: SSH2 0: SSH2_MSG_KEXDH_INIT received
6y15w: SSH2 0: signature length 271
6y15w: SSH2 0: send: len 704 (includes padlen 8)
6y15w: SSH2: kex_derive_keys complete
6y15w: SSH2 0: send: len 16 (includes padlen 10)
6y15w: SSH2 0: newkeys: mode 1
6y15w: SSH2 0: SSH2_MSG_NEWKEYS sent
6y15w: SSH2 0: waiting for SSH2_MSG_NEWKEYS
6y15w: SSH2 0: ssh_receive: 16 bytes received
6y15w: SSH2 0: input: packet len 16
6y15w: SSH2 0: partial packet 8, need 8, maclen 0
6y15w: SSH2 0: input: padlen 10
6y15w: SSH2 0: newkeys: mode 0
6y15w: SSH2 0: received packet type 21
6y15w: SSH2 0: SSH2_MSG_NEWKEYS received
6y15w: SSH2 0: ssh_receive: 36 bytes received
6y15w: SSH2 0: input: packet len 16
6y15w: SSH2 0: partial packet 16, need 0, maclen 20
6y15w: SSH2 0: MAC #3 ok
6y15w: SSH2 0: input: padlen 6
6y15w: SSH2 0: received packet type 2
6y15w: SSH2 0: ssh_receive: 52 bytes received
6y15w: SSH2 0: input: packet len 32
6y15w: SSH2 0: partial packet 16, need 16, maclen 20
6y15w: SSH2 0: MAC #4 ok
6y15w: SSH2 0: input: padlen 10
6y15w: SSH2 0: received packet type 5
6y15w: SSH2 0: send: len 32 (includes padlen 10)
6y15w: SSH2 0: done calc MAC out #3
6y15w: SSH2 0: ssh_receive: 36 bytes received
6y15w: SSH2 0: input: packet len 16
6y15w: SSH2 0: partial packet 16, need 0, maclen 20
6y15w: SSH2 0: MAC #5 ok
6y15w: SSH2 0: input: padlen 6
6y15w: SSH2 0: received packet type 2
6y15w: SSH2 0: ssh_receive: 68 bytes received
6y15w: SSH2 0: input: packet len 48
6y15w: SSH2 0: partial packet 16, need 32, maclen 20
6y15w: SSH2 0: MAC #6 ok
6y15w: SSH2 0: input: padlen 4
6y15w: SSH2 0: received packet type 50
6y15w: SSH2 0: send: len 32 (includes padlen 13)
6y15w: SSH2 0: done calc MAC out #4
6y15w: SSH2 0: ssh_receive: 36 bytes received
6y15w: SSH2 0: input: packet len 16
6y15w: SSH2 0: partial packet 16, need 0, maclen 20
6y15w: SSH2 0: MAC #7 ok
6y15w: SSH2 0: input: padlen 6
6y15w: SSH2 0: received packet type 2
6y15w: SSH2 0: ssh_receive: 100 bytes received
6y15w: SSH2 0: input: packet len 80
6y15w: SSH2 0: partial packet 16, need 64, maclen 20
6y15w: SSH2 0: MAC #8 ok
6y15w: SSH2 0: input: padlen 19
6y15w: SSH2 0: received packet type 50
6y15w: SSH2 0: send: len 16 (includes padlen 10)
6y15w: SSH2 0: done calc MAC out #5
6y15w: SSH2 0: authentication successful for dgianino
6y15w: SSH2 0: ssh_receive: 36 bytes received
6y15w: SSH2 0: input: packet len 16
6y15w: SSH2 0: partial packet 16, need 0, maclen 20
6y15w: SSH2 0: MAC #9 ok
6y15w: SSH2 0: input: padlen 6
6y15w: SSH2 0: received packet type 2
6y15w: SSH2 0: ssh_receive: 68 bytes received
6y15w: SSH2 0: input: packet len 48
6y15w: SSH2 0: partial packet 16, need 32, maclen 20
6y15w: SSH2 0: MAC #10 ok
6y15w: SSH2 0: input: padlen 19
6y15w: SSH2 0: received packet type 90
6y15w: SSH2 0: channel open request
6y15w: SSH2 0: send: len 32 (includes padlen 10)
6y15w: SSH2 0: done calc MAC out #6
6y15w: SSH2 0: ssh_receive: 36 bytes received
6y15w: SSH2 0: input: packet len 16
6y15w: SSH2 0: partial packet 16, need 0, maclen 20
6y15w: SSH2 0: MAC #11 ok
6y15w: SSH2 0: input: padlen 6
6y15w: SSH2 0: received packet type 2
6y15w: SSH2 0: ssh_receive: 84 bytes received
6y15w: SSH2 0: input: packet len 64
6y15w: SSH2 0: partial packet 16, need 48, maclen 20
6y15w: SSH2 0: MAC #12 ok
6y15w: SSH2 0: input: padlen 13
6y15w: SSH2 0: received packet type 98
6y15w: SSH2 0: send: len 16 (includes padlen 6)
6y15w: SSH2 0: done calc MAC out #7
6y15w: SSH2 0: pty-req request
6y15w: SSH2 0: setting TTY - requested: height 0, width 0; set: height 24, width 80
6y15w: SSH2 0: ssh_receive: 36 bytes received
6y15w: SSH2 0: input: packet len 16
6y15w: SSH2 0: partial packet 16, need 0, maclen 20
6y15w: SSH2 0: MAC #13 ok
6y15w: SSH2 0: input: padlen 6
6y15w: SSH2 0: received packet type 2
6y15w: SSH2 0: ssh_receive: 52 bytes received
6y15w: SSH2 0: input: packet len 32
6y15w: SSH2 0: partial packet 16, need 16, maclen 20
6y15w: SSH2 0: MAC #14 ok
6y15w: SSH2 0: input: padlen 12
6y15w: SSH2 0: received packet type 98
6y15w: SSH2 0: send: len 16 (includes padlen 6)
6y15w: SSH2 0: done calc MAC out #8
6y15w: SSH2 0: shell request
6y15w: SSH2 0: shell message received
6y15w: SSH2 0: starting shell for vty
6y15w: SSH2 0: send: len 784 (includes padlen 9)
6y15w: SSH2 0: done calc MAC out #9
6y15w: SSH2 0: send: len 48 (includes padlen 18)
6y15w: SSH2 0: done calc MAC out #10
6y15w: SSH2 0: ssh_receive: 36 bytes received
6y15w: SSH2 0: input: packet len 16
6y15w: SSH2 0: partial packet 16, need 0, maclen 20
6y15w: SSH2 0: MAC #15 ok
6y15w: SSH2 0: input: padlen 6
6y15w: SSH2 0: received packet type 2
6y15w: SSH2 0: ssh_receive: 52 bytes received
6y15w: SSH2 0: input: packet len 32
6y15w: SSH2 0: partial packet 16, need 16, maclen 20
6y15w: SSH2 0: MAC #16 ok
6y15w: SSH2 0: input: padlen 11
6y15w: SSH2 0: received packet type 94
6y15w: SSH2 0: send: len 32 (includes padlen 17)
6y15w: SSH2 0: done calc MAC out #11
6y15w: SSH2 0: send: len 32 (includes padlen 17)
6y15w: SSH2 0: done calc MAC out #12
6y15w: SSH2 0: send: len 32 (includes padlen 17)
6y15w: SSH2 0: done calc MAC out #13
6y15w: SSH2 0: send: len 32 (includes padlen 17)
6y15w: SSH2 0: done calc MAC out #14
6y15w: SSH2 0: send: len 32 (includes padlen 17)
6y15w: SSH2 0: done calc MAC out #15
6y15w: SSH2 0: send: len 32 (includes padlen 17)
6y15w: SSH2 0: done calc MAC out #16
6y15w: SSH2 0: send: len 32 (includes padlen 16)
6y15w: SSH2 0: done calc MAC out #17
6y15w: SSH2 0: send: len 32 (includes padlen 8)
6y15w: SSH2 0: done calc MAC out #18
6y15w: SSH2 0: ssh_receive: 36 bytes received
6y15w: SSH2 0: input: packet len 16
6y15w: SSH2 0: partial packet 16, need 0, maclen 20
6y15w: SSH2 0: MAC #17 ok
6y15w: SSH2 0: input: padlen 6
6y15w: SSH2 0: received packet type 2
6y15w: SSH2 0: ssh_receive: 52 bytes received
6y15w: SSH2 0: input: packet len 32
6y15w: SSH2 0: partial packet 16, need 16, maclen 20
6y15w: SSH2 0: MAC #18 ok
6y15w: SSH2 0: input: padlen 9
6y15w: SSH2 0: received packet type 94
6y15w: SSH2 0: send: len 16 (includes padlen 6)
6y15w: SSH2 0: done calc MAC out #19
6y15w: SSH2 0: send: len 16 (includes padlen 6)
6y15w: SSH2 0: done calc MAC out #20
6y15w: SSH2 0: send: len 16 (includes padlen 6)
6y15w: SSH2 0: done calc MAC out #21
6y15w: SSH2 0: send: len 16 (includes padlen 6)
6y15w: SSH2 0: done calc MAC out #22
6y15w: SSH2 0: send: len 16 (includes padlen 6)
6y15w: SSH2 0: done calc MAC out #23
6y15w: SSH2 0: send: len 16 (includes padlen 6)
6y15w: SSH2 0: done calc MAC out #24
6y15w: SSH2 0: send: len 16 (includes padlen 6)
6y15w: SSH2 0: done calc MAC out #25
6y15w: SSH2 0: send: len 16 (includes padlen 6)
6y15w: SSH2 0: done calc MAC out #26
6y15w: SSH2 0: send: len 16 (includes padlen 6)
6y15w: SSH2 0: done calc MAC out #27
6y15w: SSH0: Session disconnected - error 0x07
```

with this code:
```
import asyncssh, asyncio

async def main():
  async with asyncssh.connect(host, username=username, password=password, known_hosts=None) as conn:
    stdin, stdout, stderr = await conn.open_session(term_type="ansi")
    result = await stdout.readuntil(">")
    print("A:"+repr(result))
    stdin.write("enable\r")
    result = await stdout.readuntil("Password: ")
    print("B:"+repr(result))
    stdin.write(enable_password+"\r")
    result = await stdout.readuntil("#")
    print("C:"+repr(result))
    stdin.write("terminal pager 0\r")
    result = await stdout.readuntil("#")
    print("D:"+repr(result))
    stdin.write("terminal length 0\r")
    result = await stdout.readuntil("#")
    print("E:"+repr(result))
    stdin.write("sh run\r")
    result = await stdout.readuntil("end\r\n")
    print("F:"+repr(result))

loop = asyncio.get_event_loop()
results = loop.run_until_complete(main())
```

**Comment by ronf** [comment]
Thanks for the additional log data.

The initial handshake looks pretty normal, suggesting the key exchange and authentication to get the SSH channel connected all worked fine, as did the PTY request and communication of terminal information. After that, the system seems to send the initial banner and prompt, and then it gets a data packet (type 94) with what is probably the "enable\r" payload in it. After that, there's a bunch of what look like single byte writes, probably echoing each of the characters in "enable" followed by a '\r\n' in output packet 17. Then, output packet 18 appears to be "Password: " (note the padlen of 8, which suggests 10 bytes of actual data, compared with the previous 16 (2 bytes of data) or 17 (1 byte of data).

After this the client sends another data packet (type 94) with what appears to be 9 characters (an 8 character password plus '\r'?), and the router seems to be generating a series of output packets for each input byte. This doesn't appear to be echoed data, but it does seem to be tied to processing the password input.

The disconnect happens immediately after it receives and processes the '\r' at the end of the password. The "error 0x07" doesn't seem to tell us much, though. That seems to be a common error value when an SSH connection is closed on a Cisco device. In fact, I even found the following link that suggests there's a known bug where this can be logged on a clean close:

https://quickview.cloudapps.cisco.com/quickview/bug/CSCek43904

I also saw other reports that error 0x07 can happen when the password is bad. I know you said you see a different behavior (which doesn't result in a disconnect) when the password is bad, and you've tested that you have the right password by entering it by hand, so that doesn't seem to be the issue here. However, there does seem to be something it's not liking about us sending the password this way.

Out of curiosity, if you send '\n' instead of '\r' at the end of the lines, does that make any difference? I would have thought '\r' was the right thing to use here, but I'm just wondering if this changes the behavior at all.

One other thing to try would be to send the password and the '\r' after it in two messages, and maybe even add a delay in between to see if the disconnect is really triggered by sending the '\r' and the resulting processing of the password after it gets that.

Something else I'd suggest trying is to take out the terminal type and see if that makes any difference.
